import { z } from "zod";
import { authenticatedRequest, jsonError, jsonSuccess, requestContext } from "@/api";
import { FoundationServiceError } from "@/services/foundation";
import { createSupportAccessGrant, listSupportAccessGrants } from "@/services/enterprise-controls";
import { ecosystemMutationContext, ecosystemServiceError, mutationEnvelope } from "../../ecosystem/response";

const scope=z.object({workspace_id:z.string().uuid()}).strict();
const schema=scope.extend({support_principal_id:z.string().uuid(),confirmation_id:z.string().uuid(),reason:z.string().trim().min(1).max(1000),capabilities:z.array(z.string()).min(1).max(20),valid_until:z.string()}).strict();
export const dynamic="force-dynamic";
export async function GET(request:Request){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;try{const url=new URL(request.url);const input=scope.parse({workspace_id:url.searchParams.get("workspace_id")});return jsonSuccess(await listSupportAccessGrants(input.workspace_id,authenticated.session.principalId),context);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);if(error instanceof FoundationServiceError)return ecosystemServiceError(error,context);return jsonError("OPERATION_FAILED",context,500);}}
export async function POST(request:Request){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;const key=request.headers.get("idempotency-key")?.trim();if(!key)return jsonError("VALIDATION_FAILED",context,400);try{const input=schema.parse(await request.json());const result=await createSupportAccessGrant({workspaceId:input.workspace_id,supportPrincipalId:input.support_principal_id,confirmationId:input.confirmation_id,reason:input.reason,capabilities:input.capabilities,validUntil:input.valid_until},ecosystemMutationContext(authenticated.session.principalId,context,key,{confirmationId:input.confirmation_id}));return jsonSuccess(mutationEnvelope("support_access",result),context,result.replayed?200:201);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);if(error instanceof FoundationServiceError)return ecosystemServiceError(error,context);return jsonError("OPERATION_FAILED",context,500);}}
