import { z } from "zod";
import { authenticatedRequest, jsonError, jsonSuccess, requestContext } from "@/api";
import { FoundationServiceError } from "@/services/foundation";
import { createRelationshipType, listRelationshipTypes } from "@/services/typed-relationships";
import { ecosystemMutationContext, ecosystemServiceError, mutationEnvelope } from "../ecosystem/response";

const entity=z.enum(["page","issue","todo","calendar_entry","canvas"]);
const scope=z.object({workspace_id:z.string().uuid(),project_id:z.string().uuid()}).strict();
const schema=scope.extend({type_key:z.string(),display_name:z.string(),source_entity_types:z.array(entity).min(1),target_entity_types:z.array(entity).min(1),symmetric:z.boolean().optional(),inverse_type_key:z.string().nullable().optional()}).strict();
export const dynamic="force-dynamic";
export async function GET(request:Request){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;try{const url=new URL(request.url);const input=scope.parse({workspace_id:url.searchParams.get("workspace_id"),project_id:url.searchParams.get("project_id")});return jsonSuccess(await listRelationshipTypes({workspaceId:input.workspace_id,projectId:input.project_id,includeDisabled:url.searchParams.get("include_disabled")==="true"},authenticated.session.principalId),context);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);if(error instanceof FoundationServiceError)return ecosystemServiceError(error,context);return jsonError("OPERATION_FAILED",context,500);}}
export async function POST(request:Request){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;const key=request.headers.get("idempotency-key")?.trim();if(!key)return jsonError("VALIDATION_FAILED",context,400);try{const input=schema.parse(await request.json());const result=await createRelationshipType({workspaceId:input.workspace_id,projectId:input.project_id,typeKey:input.type_key,displayName:input.display_name,sourceEntityTypes:input.source_entity_types,targetEntityTypes:input.target_entity_types,symmetric:input.symmetric,inverseTypeKey:input.inverse_type_key},ecosystemMutationContext(authenticated.session.principalId,context,key));return jsonSuccess(mutationEnvelope("relationship_type",result),context,result.replayed?200:201);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);if(error instanceof FoundationServiceError)return ecosystemServiceError(error,context);return jsonError("OPERATION_FAILED",context,500);}}
