import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Pool } from "pg";
import { postgresPool } from "@/db/postgres";
import { establishTenantContext } from "@/db/tenant";
import { newFolioId } from "@/lib/folio-ids";
import { authorizeEcosystemProjectCapability, authorizeWorkspaceOwner } from "@/services/ecosystem-access";
import { FoundationServiceError } from "@/services/foundation/errors";
import { findIdempotentResult, inTransaction, lockIdempotencyKey, recordMutation, requestDigest } from "@/services/foundation/internal";
import type { MutationContext, MutationResult } from "@/services/foundation/types";

export type AuditExport={id:string;workspaceId:string;projectId:string|null;requestedByPrincipalId:string;format:"jsonl"|"csv";filters:Record<string,unknown>;state:"pending"|"running"|"succeeded"|"failed"|"expired"|"canceled";objectKey:string|null;contentHash:string|null;rowCount:number|null;expiresAt:string;revision:number;createdAt:string;startedAt:string|null;completedAt:string|null;lastErrorCode:string|null;lastErrorMessage:string|null};
type ExportRow={id:string;workspace_id:string;project_id:string|null;requested_by_principal_id:string;format:AuditExport["format"];filters:Record<string,unknown>;state:AuditExport["state"];object_key:string|null;content_hash:string|null;row_count:string|null;expires_at:Date;revision:string;created_at:Date;started_at:Date|null;completed_at:Date|null;last_error_code:string|null;last_error_message:string|null};
type ActivityRow={id:string;workspace_id:string;project_id:string|null;actor_principal_id:string;authorizing_principal_id:string|null;source:string;action:string;target_type:string;target_id:string;input_summary:Record<string,unknown>;result_summary:Record<string,unknown>;request_id:string;trace_id:string|null;confirmation_id:string|null;created_at:Date};
const columns=`id,workspace_id,project_id,requested_by_principal_id,format,filters,state,object_key,content_hash,row_count,expires_at,revision,created_at,started_at,completed_at,last_error_code,last_error_message`;
const map=(row:ExportRow):AuditExport=>({id:row.id,workspaceId:row.workspace_id,projectId:row.project_id,requestedByPrincipalId:row.requested_by_principal_id,format:row.format,filters:row.filters,state:row.state,objectKey:row.object_key,contentHash:row.content_hash,rowCount:row.row_count===null?null:Number(row.row_count),expiresAt:row.expires_at.toISOString(),revision:Number(row.revision),createdAt:row.created_at.toISOString(),startedAt:row.started_at?.toISOString()??null,completedAt:row.completed_at?.toISOString()??null,lastErrorCode:row.last_error_code,lastErrorMessage:row.last_error_message});

function exportRoot(){return path.resolve(process.env.AUDIT_EXPORT_ROOT?.trim()||path.join(process.cwd(),".local-data","audit-exports"));}
function dateFilter(value:unknown,label:string):string|null{if(value===undefined||value===null||value==="")return null;if(typeof value!=="string")throw new FoundationServiceError("VALIDATION_FAILED",`${label} must be an ISO date-time.`);const date=new Date(value);if(Number.isNaN(date.getTime()))throw new FoundationServiceError("VALIDATION_FAILED",`${label} must be an ISO date-time.`);return date.toISOString();}
function normalizedFilters(value:Record<string,unknown>|undefined){const filters=value??{};const start=dateFilter(filters.start,"Export start");const end=dateFilter(filters.end,"Export end");if(start&&end&&new Date(end)<=new Date(start))throw new FoundationServiceError("VALIDATION_FAILED","Export end must follow start.");const actions=Array.isArray(filters.actions)?[...new Set(filters.actions.filter((item):item is string=>typeof item==="string"&&item.length<=200))].slice(0,100):[];const targetTypes=Array.isArray(filters.targetTypes)?[...new Set(filters.targetTypes.filter((item):item is string=>typeof item==="string"&&item.length<=100))].slice(0,100):[];const limit=typeof filters.limit==="number"&&Number.isSafeInteger(filters.limit)?Math.max(1,Math.min(filters.limit,100000)):50000;return{start,end,actions,targetTypes,limit};}
async function authorizeExportScope(client:import("pg").PoolClient,input:{workspaceId:string;projectId:string|null;principalId:string}){if(input.projectId){await authorizeEcosystemProjectCapability(client,{workspaceId:input.workspaceId,projectId:input.projectId,principalId:input.principalId,capability:"audit.export"});}else await authorizeWorkspaceOwner(client,{workspaceId:input.workspaceId,principalId:input.principalId});}

export async function requestAuditExport(raw:{workspaceId:string;projectId?:string|null;format:"jsonl"|"csv";filters?:Record<string,unknown>;expiresInHours?:number},context:MutationContext,pool:Pool=postgresPool()):Promise<MutationResult<AuditExport>>{const filters=normalizedFilters(raw.filters);const expiresInHours=Math.max(1,Math.min(raw.expiresInHours??24,168));const input={workspaceId:raw.workspaceId,projectId:raw.projectId??null,format:raw.format,filters,expiresInHours};const operation="audit_export.request";const digest=requestDigest(input);return inTransaction(pool,async(client)=>{await establishTenantContext(client,input.workspaceId,context.actorPrincipalId);await lockIdempotencyKey(client,context.actorPrincipalId,operation,context.idempotencyKey);const replay=await findIdempotentResult<AuditExport>(client,{workspaceId:input.workspaceId,projectId:input.projectId??undefined,projectAgnostic:!input.projectId,principalId:context.actorPrincipalId,operation,key:context.idempotencyKey,digest});if(replay)return replay;await authorizeExportScope(client,{workspaceId:input.workspaceId,projectId:input.projectId,principalId:context.actorPrincipalId});const id=newFolioId();const jobId=newFolioId();const result=await client.query<ExportRow>(`INSERT INTO audit_export_requests(id,workspace_id,project_id,requested_by_principal_id,format,filters,expires_at) VALUES($1,$2,$3,$4,$5,$6,now()+make_interval(hours=>$7)) RETURNING ${columns}`,[id,input.workspaceId,input.projectId,context.actorPrincipalId,input.format,input.filters,expiresInHours]);await client.query(`INSERT INTO jobs(id,workspace_id,project_id,kind,payload,deduplication_key,status,available_at,max_attempts) VALUES($1,$2,$3,'audit.export',$4,$5,'pending',now(),3)`,[jobId,input.workspaceId,input.projectId,{exportId:id},`audit-export:${id}`]);const data=map(result.rows[0]!);return recordMutation(client,{workspaceId:input.workspaceId,projectId:input.projectId??undefined,context,operation,digest,action:operation,targetType:"audit_export",targetId:id,aggregateType:"audit_export",aggregateRevision:1,eventType:"audit_export.requested.v1",inputSummary:{format:input.format,projectScoped:Boolean(input.projectId),filters:{...input.filters,actions:(input.filters.actions as string[]).length,targetTypes:(input.filters.targetTypes as string[]).length}},resultSummary:{auditExportId:id,jobId,state:data.state,expiresAt:data.expiresAt},data});});}

export async function listAuditExports(input:{workspaceId:string;projectId?:string|null},principalId:string,pool:Pool=postgresPool()):Promise<AuditExport[]>{return inTransaction(pool,async(client)=>{await establishTenantContext(client,input.workspaceId,principalId);await authorizeExportScope(client,{workspaceId:input.workspaceId,projectId:input.projectId??null,principalId});await client.query(`UPDATE audit_export_requests SET state='expired',revision=revision+1 WHERE workspace_id=$1 AND state='succeeded' AND expires_at<=now()`,[input.workspaceId]);const result=await client.query<ExportRow>(`SELECT ${columns} FROM audit_export_requests WHERE workspace_id=$1 AND project_id IS NOT DISTINCT FROM $2 ORDER BY created_at DESC,id`,[input.workspaceId,input.projectId??null]);return result.rows.map(map);});}

export async function readAuditExport(input:{workspaceId:string;exportId:string},principalId:string,pool:Pool=postgresPool()):Promise<AuditExport>{return inTransaction(pool,async(client)=>{await establishTenantContext(client,input.workspaceId,principalId);const result=await client.query<ExportRow>(`SELECT ${columns} FROM audit_export_requests WHERE workspace_id=$1 AND id=$2`,[input.workspaceId,input.exportId]);const row=result.rows[0];if(!row)throw new FoundationServiceError("NOT_FOUND","Audit export was not found.");await authorizeExportScope(client,{workspaceId:input.workspaceId,projectId:row.project_id,principalId});return map(row);});}

function csvCell(value:unknown){const serialized=typeof value==="string"?value:value===undefined||value===null?"":JSON.stringify(value);return `"${serialized.replaceAll('"','""')}"`;}
function serializeActivity(rows:ActivityRow[],format:AuditExport["format"]){if(format==="jsonl")return rows.map((row)=>JSON.stringify({...row,created_at:row.created_at.toISOString()})).join("\n")+"\n";const headers=["id","workspace_id","project_id","actor_principal_id","authorizing_principal_id","source","action","target_type","target_id","input_summary","result_summary","request_id","trace_id","confirmation_id","created_at"];return [headers.join(","),...rows.map((row)=>headers.map((header)=>csvCell(header==="created_at"?row.created_at.toISOString():(row as unknown as Record<string,unknown>)[header])).join(","))].join("\n")+"\n";}

export async function executeAuditExport(exportId:string,pool:Pool=postgresPool()):Promise<{exportId:string;rowCount:number;contentHash:string;objectKey:string}>{const prepared=await inTransaction(pool,async(client)=>{await client.query("SET LOCAL ROLE folio_worker");const result=await client.query<ExportRow>(`UPDATE audit_export_requests SET state='running',started_at=coalesce(started_at,now()),revision=revision+1,last_error_code=NULL,last_error_message=NULL WHERE id=$1 AND state IN ('pending','failed') AND expires_at>now() RETURNING ${columns}`,[exportId]);const row=result.rows[0];if(!row)throw new FoundationServiceError("CONFLICT","Audit export is not pending, retryable, or unexpired.");const filters=normalizedFilters(row.filters);const activities=await client.query<ActivityRow>(`SELECT id,workspace_id,project_id,actor_principal_id,authorizing_principal_id,source,action,target_type,target_id,input_summary,result_summary,request_id,trace_id,confirmation_id,created_at FROM activity_events WHERE workspace_id=$1 AND ($2::uuid IS NULL OR project_id=$2) AND ($3::timestamptz IS NULL OR created_at>=$3) AND ($4::timestamptz IS NULL OR created_at<$4) AND (cardinality($5::text[])=0 OR action=ANY($5)) AND (cardinality($6::text[])=0 OR target_type=ANY($6)) ORDER BY created_at,id LIMIT $7`,[row.workspace_id,row.project_id,filters.start,filters.end,filters.actions,filters.targetTypes,filters.limit]);return{row,activities:activities.rows};});try{const content=serializeActivity(prepared.activities,prepared.row.format);const hash=createHash("sha256").update(content).digest("hex");const extension=prepared.row.format==="jsonl"?"jsonl":"csv";const objectKey=`${prepared.row.workspace_id}/${prepared.row.id}.${extension}`;const root=exportRoot();const filePath=path.resolve(root,objectKey);if(!filePath.startsWith(`${root}${path.sep}`))throw new FoundationServiceError("VALIDATION_FAILED","Audit export path is invalid.");await mkdir(path.dirname(filePath),{recursive:true});await writeFile(filePath,content,{encoding:"utf8",mode:0o600});await inTransaction(pool,async(client)=>{await client.query("SET LOCAL ROLE folio_worker");await client.query(`UPDATE audit_export_requests SET state='succeeded',object_key=$2,content_hash=$3,row_count=$4,completed_at=now(),revision=revision+1 WHERE id=$1`,[exportId,objectKey,hash,prepared.activities.length]);});return{exportId,rowCount:prepared.activities.length,contentHash:hash,objectKey};}catch(error){await inTransaction(pool,async(client)=>{await client.query("SET LOCAL ROLE folio_worker");await client.query(`UPDATE audit_export_requests SET state='failed',last_error_code=$2,last_error_message=$3,completed_at=now(),revision=revision+1 WHERE id=$1`,[exportId,error instanceof FoundationServiceError?error.code:"AUDIT_EXPORT_FAILED",error instanceof Error?error.message.slice(0,500):"Audit export failed"]);});throw error;}}

export async function readAuditExportContent(input:{workspaceId:string;exportId:string},principalId:string,pool:Pool=postgresPool()):Promise<{export:AuditExport;content:Buffer}>{const item=await readAuditExport(input,principalId,pool);if(item.state!=="succeeded"||!item.objectKey||new Date(item.expiresAt)<=new Date())throw new FoundationServiceError("CONFLICT","Audit export content is unavailable or expired.");const root=exportRoot();const filePath=path.resolve(root,item.objectKey);if(!filePath.startsWith(`${root}${path.sep}`))throw new FoundationServiceError("CONFLICT","Audit export path is invalid.");const content=await readFile(filePath);const hash=createHash("sha256").update(content).digest("hex");if(hash!==item.contentHash)throw new FoundationServiceError("CONFLICT","Audit export integrity check failed.");return{export:item,content};}
