import { createHash } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import { postgresPool } from "@/db/postgres";
import { establishTenantContext } from "@/db/tenant";
import {
  createGitHubBlob,
  createGitHubCommit,
  createGitHubPullRequest,
  createGitHubRef,
  createGitHubTree,
  getGitHubCommit,
  getGitHubRef,
  GitHubProviderError,
  updateGitHubRef,
} from "@/integrations/github/app-client";
import { findGitHubPullRequest, getGitHubContentMetadata } from "@/integrations/github/write-client";
import { newFolioId } from "@/lib/folio-ids";
import { authorizeEcosystemProjectCapability } from "@/services/ecosystem-access";
import { FoundationServiceError } from "@/services/foundation/errors";
import { inTransaction, requestDigest } from "@/services/foundation/internal";
import type { GitFileOperation } from "@/services/github-write-previews";
import { pathMatchesMarkdownScope } from "@/services/github-path-policy";

type PreparedRow={
  id:string;workspace_id:string;project_id:string;repository_link_id:string;selected_branch_id:string;
  operation_kind:"commit_and_pull_request"|"direct_update";base_head_oid:string;target_branch:string;
  pull_request_base_branch:string|null;commit_message:string;pull_request_title:string|null;
  pull_request_body:string|null;file_operations:GitFileOperation[];action_digest:string;
  state:string;actor_principal_id:string;authorizing_principal_id:string;policy_snapshot:Record<string,unknown>;
  target_ref_oid:string|null;provider_result:Record<string,unknown>|null;revision:string;
};
type ExecutionContext={
  prepared:PreparedRow;providerInstallationId:number;ownerLogin:string;repositoryName:string;
  selectedBranchName:string;writePolicy:string;rulesVersion:number;includeRules:string[];excludeRules:string[];
  installationPermissions:Record<string,string>;repositoryPermissions:Record<string,boolean>;
  linkState:string;branchState:string;repositoryState:string;installationState:string;
};
type StepKind="create_blob"|"create_tree"|"create_commit"|"create_ref"|"update_ref"|"create_pull_request"|"reconcile_after_write";
type StepRow={state:string;provider_identifier:string|null;response_summary:Record<string,unknown>|null;request_digest:string};

async function workerTransaction<T>(pool:Pool,work:(client:PoolClient)=>Promise<T>){return inTransaction(pool,async(client)=>{await client.query("SET LOCAL ROLE folio_worker");return work(client);});}

async function loadContext(preparedOperationId:string,pool:Pool):Promise<ExecutionContext>{return workerTransaction(pool,async(client)=>{const result=await client.query<PreparedRow&{provider_installation_id:string;owner_login:string;repository_name:string;selected_branch_name:string;write_policy:string;rules_version:string;include_rules:string[];exclude_rules:string[];installation_permissions:Record<string,string>;repository_permissions:Record<string,boolean>;link_state:string;branch_state:string;repository_state:string;installation_state:string}>(`SELECT prepared.*,installation.provider_installation_id,repository.owner_login,repository.name repository_name,
    branch.branch_name selected_branch_name,link.write_policy,link.rules_version,link.include_rules,link.exclude_rules,
    installation.permissions installation_permissions,repository.permissions repository_permissions,
    link.state link_state,branch.state branch_state,repository.state repository_state,installation.state installation_state
    FROM prepared_git_operations prepared
    JOIN project_repository_links link ON link.workspace_id=prepared.workspace_id AND link.project_id=prepared.project_id AND link.id=prepared.repository_link_id
    JOIN selected_git_branches branch ON branch.workspace_id=prepared.workspace_id AND branch.project_id=prepared.project_id AND branch.id=prepared.selected_branch_id
    JOIN github_repositories repository ON repository.workspace_id=link.workspace_id AND repository.id=link.repository_id
    JOIN github_app_installations installation ON installation.workspace_id=repository.workspace_id AND installation.id=repository.installation_id
    WHERE prepared.id=$1 FOR UPDATE OF prepared`,[preparedOperationId]);const row=result.rows[0];if(!row)throw new FoundationServiceError("NOT_FOUND","Prepared Git operation was not found.");if(row.state==="succeeded")return{prepared:row,providerInstallationId:Number(row.provider_installation_id),ownerLogin:row.owner_login,repositoryName:row.repository_name,selectedBranchName:row.selected_branch_name,writePolicy:row.write_policy,rulesVersion:Number(row.rules_version),includeRules:row.include_rules,excludeRules:row.exclude_rules,installationPermissions:row.installation_permissions,repositoryPermissions:row.repository_permissions,linkState:row.link_state,branchState:row.branch_state,repositoryState:row.repository_state,installationState:row.installation_state};if(!["executing","failed"].includes(row.state))throw new FoundationServiceError("CONFLICT","Prepared Git operation is not queued for execution.");await client.query(`UPDATE prepared_git_operations SET state='executing',revision=revision+CASE WHEN state='failed' THEN 1 ELSE 0 END,updated_at=now(),last_error_code=NULL,last_error_message=NULL WHERE id=$1`,[row.id]);return{prepared:{...row,state:"executing"},providerInstallationId:Number(row.provider_installation_id),ownerLogin:row.owner_login,repositoryName:row.repository_name,selectedBranchName:row.selected_branch_name,writePolicy:row.write_policy,rulesVersion:Number(row.rules_version),includeRules:row.include_rules,excludeRules:row.exclude_rules,installationPermissions:row.installation_permissions,repositoryPermissions:row.repository_permissions,linkState:row.link_state,branchState:row.branch_state,repositoryState:row.repository_state,installationState:row.installation_state};});}

async function authorizeExecution(context:ExecutionContext,pool:Pool){await inTransaction(pool,async(client)=>{await establishTenantContext(client,context.prepared.workspace_id,context.prepared.actor_principal_id);const capabilities=["repository.markdown.commit",...(context.prepared.operation_kind==="commit_and_pull_request"?["repository.branch.create","repository.pull_request.open"]:[])] as const;for(const capability of capabilities){await authorizeEcosystemProjectCapability(client,{workspaceId:context.prepared.workspace_id,projectId:context.prepared.project_id,principalId:context.prepared.actor_principal_id,capability});await client.query("SELECT folio.set_transaction_context($1,$2)",[context.prepared.workspace_id,context.prepared.authorizing_principal_id]);await authorizeEcosystemProjectCapability(client,{workspaceId:context.prepared.workspace_id,projectId:context.prepared.project_id,principalId:context.prepared.authorizing_principal_id,capability});await client.query("SELECT folio.set_transaction_context($1,$2)",[context.prepared.workspace_id,context.prepared.actor_principal_id]);}});}

function validateCurrentPolicy(context:ExecutionContext){const snapshot=context.prepared.policy_snapshot;const rulesVersion=typeof snapshot.rulesVersion==="number"?snapshot.rulesVersion:Number(snapshot.rulesVersion);const writePolicy=typeof snapshot.writePolicy==="string"?snapshot.writePolicy:null;if(context.linkState!=="active"||context.branchState!=="enabled"||context.repositoryState!=="available"||context.installationState!=="active")throw new FoundationServiceError("GITHUB_PERMISSION_CHANGED","Repository or installation is no longer active.");if(rulesVersion!==context.rulesVersion||writePolicy!==context.writePolicy)throw new FoundationServiceError("PATH_POLICY_CHANGED","Repository path or write policy changed after preparation.");if(context.installationPermissions.contents!=="write"||context.repositoryPermissions.push!==true)throw new FoundationServiceError("GITHUB_PERMISSION_CHANGED","GitHub contents write permission is unavailable.");if(context.prepared.operation_kind==="commit_and_pull_request"&&context.installationPermissions.pull_requests!=="write")throw new FoundationServiceError("GITHUB_PERMISSION_CHANGED","GitHub pull request write permission is unavailable.");if(context.prepared.operation_kind==="direct_update"&&context.writePolicy!=="direct_allowed")throw new FoundationServiceError("PATH_POLICY_CHANGED","Direct updates are no longer permitted.");for(const operation of context.prepared.file_operations)if(!pathMatchesMarkdownScope(operation.path,context.includeRules,context.excludeRules))throw new FoundationServiceError("PATH_POLICY_CHANGED","A prepared path is no longer writable.",{path:operation.path});}

function providerError(error:unknown,stage:"read"|"ref"):never{if(error instanceof GitHubProviderError){if(error.code==="GITHUB_RATE_LIMITED")throw new FoundationServiceError("PROVIDER_RATE_LIMITED",error.message,{retryable:true});if(error.code==="GITHUB_PROVIDER_UNAVAILABLE")throw new FoundationServiceError("PROVIDER_UNAVAILABLE",error.message,{retryable:true});if(error.code==="GITHUB_FORBIDDEN"||error.code==="GITHUB_UNAUTHORIZED")throw new FoundationServiceError(stage==="ref"?"BRANCH_PROTECTED":"GITHUB_PERMISSION_CHANGED",error.message,{providerCode:error.code});if(error.code==="GITHUB_CONFLICT")throw new FoundationServiceError(stage==="ref"?"TARGET_REF_CHANGED":"CONFLICT",error.message,{providerCode:error.code});if(error.code==="GITHUB_NOT_FOUND")throw new FoundationServiceError("NOT_FOUND",error.message);throw new FoundationServiceError("CONFLICT",error.message,{providerCode:error.code});}throw error;}

async function readStep(pool:Pool,prepared:PreparedRow,kind:StepKind,key:string){return workerTransaction(pool,async(client)=>{const result=await client.query<StepRow>(`SELECT state,provider_identifier,response_summary,request_digest FROM git_provider_operations WHERE prepared_operation_id=$1 AND step_kind=$2 AND step_key=$3`,[prepared.id,kind,key]);return result.rows[0]??null;});}
async function beginStep(pool:Pool,prepared:PreparedRow,kind:StepKind,key:string,digest:string){return workerTransaction(pool,async(client)=>{const result=await client.query<StepRow>(`INSERT INTO git_provider_operations(id,workspace_id,project_id,prepared_operation_id,step_kind,step_key,request_digest,state,attempt_count,available_at) VALUES($1,$2,$3,$4,$5,$6,$7,'running',1,now()) ON CONFLICT(prepared_operation_id,step_kind,step_key) DO UPDATE SET state='running',attempt_count=git_provider_operations.attempt_count+1,updated_at=now(),last_error_code=NULL,last_error_message=NULL WHERE git_provider_operations.state<>'succeeded' AND git_provider_operations.request_digest=excluded.request_digest RETURNING state,provider_identifier,response_summary,request_digest`,[newFolioId(),prepared.workspace_id,prepared.project_id,prepared.id,kind,key,digest]);if(!result.rows[0]){const existing=await client.query<StepRow>(`SELECT state,provider_identifier,response_summary,request_digest FROM git_provider_operations WHERE prepared_operation_id=$1 AND step_kind=$2 AND step_key=$3`,[prepared.id,kind,key]);const row=existing.rows[0];if(!row||row.request_digest!==digest)throw new FoundationServiceError("IDEMPOTENCY_CONFLICT","Git provider step key was reused with different input.");return row;}return result.rows[0];});}
async function succeedStep(pool:Pool,prepared:PreparedRow,kind:StepKind,key:string,providerIdentifier:string|null,summary:Record<string,unknown>){await workerTransaction(pool,async(client)=>{await client.query(`UPDATE git_provider_operations SET state='succeeded',provider_identifier=$4,response_summary=$5,completed_at=now(),updated_at=now(),last_error_code=NULL,last_error_message=NULL WHERE prepared_operation_id=$1 AND step_kind=$2 AND step_key=$3`,[prepared.id,kind,key,providerIdentifier,summary]);});}
async function failStep(pool:Pool,prepared:PreparedRow,kind:StepKind,key:string,error:unknown){await workerTransaction(pool,async(client)=>{await client.query(`UPDATE git_provider_operations SET state='failed',last_error_code=$4,last_error_message=$5,updated_at=now() WHERE prepared_operation_id=$1 AND step_kind=$2 AND step_key=$3 AND state<>'succeeded'`,[prepared.id,kind,key,error instanceof FoundationServiceError?error.code:"PROVIDER_STEP_FAILED",error instanceof Error?error.message.slice(0,500):"Provider step failed"]);}).catch(()=>undefined);}

async function providerStep<T>(pool:Pool,prepared:PreparedRow,kind:StepKind,key:string,input:unknown,execute:()=>Promise<{identifier:string|null;summary:Record<string,unknown>;value:T}>):Promise<T>{const digest=requestDigest(input);const existing=await readStep(pool,prepared,kind,key);if(existing?.state==="succeeded"){return (existing.response_summary?.value??existing.provider_identifier) as T;}await beginStep(pool,prepared,kind,key,digest);try{const result=await execute();await succeedStep(pool,prepared,kind,key,result.identifier,{...result.summary,value:result.value});return result.value;}catch(error){await failStep(pool,prepared,kind,key,error);throw error;}}

async function currentRef(context:ExecutionContext,branch:string){try{return(await getGitHubRef(context.providerInstallationId,context.ownerLogin,context.repositoryName,`heads/${branch}`)).data.object.sha;}catch(error){if(error instanceof GitHubProviderError&&error.code==="GITHUB_NOT_FOUND")return null;providerError(error,"read");}}

async function verifyBaseBlobs(context:ExecutionContext){for(const operation of context.prepared.file_operations){let current;try{current=await getGitHubContentMetadata(context.providerInstallationId,context.ownerLogin,context.repositoryName,operation.path,context.prepared.base_head_oid);}catch(error){providerError(error,"read");}const expected=operation.baseBlobOid;if((current?.sha??null)!==expected)throw new FoundationServiceError("BLOB_CHANGED","A prepared Markdown blob changed before execution.",{path:operation.path,preparedBlobOid:expected,currentBlobOid:current?.sha??null});}}

async function finishSuccess(pool:Pool,context:ExecutionContext,result:Record<string,unknown>){return workerTransaction(pool,async(client)=>{const updated=await client.query<{revision:string}>(`UPDATE prepared_git_operations SET state='succeeded',provider_result=$2,revision=revision+1,completed_at=now(),updated_at=now(),last_error_code=NULL,last_error_message=NULL WHERE id=$1 AND state IN ('executing','failed','succeeded') RETURNING revision`,[context.prepared.id,result]);if(!updated.rows[0])throw new FoundationServiceError("CONFLICT","Prepared Git operation lost its execution state.");const revision=Number(updated.rows[0].revision);if(context.prepared.operation_kind==="direct_update"&&typeof result.commitSha==="string")await client.query(`INSERT INTO jobs(id,workspace_id,project_id,kind,payload,deduplication_key,status,priority,max_attempts,available_at) VALUES($1,$2,$3,'github.branch.reconcile',$4,$5,'pending',40,8,now()) ON CONFLICT DO NOTHING`,[newFolioId(),context.prepared.workspace_id,context.prepared.project_id,{selectedBranchId:context.prepared.selected_branch_id,headHint:result.commitSha},`github-reconcile:${context.prepared.selected_branch_id}:${result.commitSha}`]);const activityId=newFolioId();const outboxId=newFolioId();const requestId=newFolioId();await client.query(`INSERT INTO activity_events(id,workspace_id,project_id,actor_principal_id,authorizing_principal_id,source,action,target_type,target_id,input_summary,result_summary,request_id,trace_id,confirmation_id) VALUES($1,$2,$3,$4,$5,'worker','github.write.executed','prepared_git_operation',$6,$7,$8,$9,$10,$11)`,[activityId,context.prepared.workspace_id,context.prepared.project_id,context.prepared.actor_principal_id,context.prepared.authorizing_principal_id,context.prepared.id,{operationKind:context.prepared.operation_kind,fileCount:context.prepared.file_operations.length,targetBranch:context.prepared.target_branch},result,requestId,`github-write:${context.prepared.id}`,null]);await client.query(`INSERT INTO outbox_events(id,workspace_id,project_id,aggregate_type,aggregate_id,aggregate_revision,event_type,actor_principal_id,authorizing_principal_id,request_id,trace_id,payload) VALUES($1,$2,$3,'prepared_git_operation',$4,$5,'github.write_executed.v1',$6,$7,$8,$9,$10)`,[outboxId,context.prepared.workspace_id,context.prepared.project_id,context.prepared.id,revision,context.prepared.actor_principal_id,context.prepared.authorizing_principal_id,requestId,`github-write:${context.prepared.id}`,result]);return{...result,revision,activityId,outboxId};});}

async function markFailure(pool:Pool,prepared:PreparedRow,error:unknown){await workerTransaction(pool,async(client)=>{await client.query(`UPDATE prepared_git_operations SET state='failed',revision=revision+1,updated_at=now(),last_error_code=$2,last_error_message=$3 WHERE id=$1 AND state<>'succeeded'`,[prepared.id,error instanceof FoundationServiceError?error.code:"GITHUB_WRITE_FAILED",error instanceof Error?error.message.slice(0,500):"Git write failed"]);}).catch(()=>undefined);}

export async function executePreparedGitWrite(preparedOperationId:string,pool:Pool=postgresPool()):Promise<Record<string,unknown>>{
  const context=await loadContext(preparedOperationId,pool);if(context.prepared.state==="succeeded")return context.prepared.provider_result??{preparedOperationId};
  try{
    await authorizeExecution(context,pool);validateCurrentPolicy(context);
    const knownCommit=await readStep(pool,context.prepared,"create_commit","commit");const knownCommitSha=knownCommit?.state==="succeeded"?knownCommit.provider_identifier:null;
    const baseRef=await currentRef(context,context.selectedBranchName);
    const directAlreadyApplied=context.prepared.operation_kind==="direct_update"&&knownCommitSha!==null&&baseRef===knownCommitSha;
    if(!directAlreadyApplied&&baseRef!==context.prepared.base_head_oid)throw new FoundationServiceError("BASE_REF_CHANGED","Base branch changed after preparation.",{preparedHeadOid:context.prepared.base_head_oid,currentHeadOid:baseRef});
    const targetRef=await currentRef(context,context.prepared.target_branch);
    const targetAlreadyApplied=knownCommitSha!==null&&targetRef===knownCommitSha;
    if(context.prepared.operation_kind==="commit_and_pull_request"&&!targetAlreadyApplied&&targetRef!==context.prepared.target_ref_oid)throw new FoundationServiceError("TARGET_REF_CHANGED","Working branch changed after preparation.",{preparedTargetOid:context.prepared.target_ref_oid,currentTargetOid:targetRef});

    let commitSha=knownCommitSha;
    if(!commitSha){
      await verifyBaseBlobs(context);
      let baseCommit;try{baseCommit=await getGitHubCommit(context.providerInstallationId,context.ownerLogin,context.repositoryName,context.prepared.base_head_oid);}catch(error){providerError(error,"read");}
      const treeEntries:Array<{path:string;mode:"100644";type:"blob";sha:string|null}>=[];
      for(const operation of context.prepared.file_operations){if(operation.operation==="delete"){treeEntries.push({path:operation.path,mode:"100644",type:"blob",sha:null});continue;}const blobSha=await providerStep(pool,context.prepared,"create_blob",operation.path,{path:operation.path,contentHash:operation.contentHash},async()=>{let created;try{created=await createGitHubBlob(context.providerInstallationId,context.ownerLogin,context.repositoryName,operation.content);}catch(error){providerError(error,"read");}return{identifier:created.data.sha,summary:{sha:created.data.sha},value:created.data.sha};});treeEntries.push({path:operation.path,mode:"100644",type:"blob",sha:blobSha});}
      const treeSha=await providerStep(pool,context.prepared,"create_tree","tree",{baseTree:baseCommit.data.tree.sha,entries:treeEntries},async()=>{let created;try{created=await createGitHubTree(context.providerInstallationId,context.ownerLogin,context.repositoryName,baseCommit.data.tree.sha,treeEntries);}catch(error){providerError(error,"read");}return{identifier:created.data.sha,summary:{sha:created.data.sha},value:created.data.sha};});
      const message=`${context.prepared.commit_message}\n\nFolio-Actor: ${context.prepared.actor_principal_id}\nFolio-Authorizer: ${context.prepared.authorizing_principal_id}\nFolio-Operation: ${context.prepared.id}`;
      commitSha=await providerStep(pool,context.prepared,"create_commit","commit",{treeSha,parent:context.prepared.base_head_oid,message},async()=>{let created;try{created=await createGitHubCommit(context.providerInstallationId,context.ownerLogin,context.repositoryName,message,treeSha,[context.prepared.base_head_oid]);}catch(error){providerError(error,"read");}return{identifier:created.data.sha,summary:{sha:created.data.sha},value:created.data.sha};});
    }

    if(context.prepared.operation_kind==="direct_update"){
      if(!directAlreadyApplied){const current=await currentRef(context,context.selectedBranchName);if(current!==context.prepared.base_head_oid&&current!==commitSha)throw new FoundationServiceError("BASE_REF_CHANGED","Base branch moved before ref update.",{currentHeadOid:current});if(current!==commitSha)await providerStep(pool,context.prepared,"update_ref",context.selectedBranchName,{branch:context.selectedBranchName,base:context.prepared.base_head_oid,commitSha},async()=>{try{const updated=await updateGitHubRef(context.providerInstallationId,context.ownerLogin,context.repositoryName,context.selectedBranchName,commitSha!,false);return{identifier:updated.data.object.sha,summary:{sha:updated.data.object.sha},value:updated.data.object.sha};}catch(error){providerError(error,"ref");}});}
      return finishSuccess(pool,context,{preparedOperationId:context.prepared.id,commitSha,targetBranch:context.selectedBranchName,direct:true});
    }

    if(!targetAlreadyApplied){const current=await currentRef(context,context.prepared.target_branch);if(current!==null&&current!==commitSha)throw new FoundationServiceError("TARGET_REF_CHANGED","Working branch now points to a different commit.",{currentTargetOid:current});if(current===null)await providerStep(pool,context.prepared,"create_ref",context.prepared.target_branch,{branch:context.prepared.target_branch,commitSha},async()=>{try{const created=await createGitHubRef(context.providerInstallationId,context.ownerLogin,context.repositoryName,context.prepared.target_branch,commitSha!);return{identifier:created.data.object.sha,summary:{sha:created.data.object.sha},value:created.data.object.sha};}catch(error){providerError(error,"ref");}});}
    let pull=await findGitHubPullRequest(context.providerInstallationId,context.ownerLogin,context.repositoryName,{head:context.prepared.target_branch,base:context.prepared.pull_request_base_branch!}).catch((error)=>providerError(error,"read"));
    if(!pull){pull=await providerStep(pool,context.prepared,"create_pull_request","pull-request",{head:context.prepared.target_branch,base:context.prepared.pull_request_base_branch,title:context.prepared.pull_request_title},async()=>{try{const created=await createGitHubPullRequest(context.providerInstallationId,context.ownerLogin,context.repositoryName,{title:context.prepared.pull_request_title||context.prepared.commit_message,body:context.prepared.pull_request_body??undefined,head:context.prepared.target_branch,base:context.prepared.pull_request_base_branch!});return{identifier:String(created.data.number),summary:{number:created.data.number,nodeId:created.data.node_id,htmlUrl:created.data.html_url,state:created.data.state,title:created.data.title,head:created.data.head.ref,base:created.data.base.ref,createdAt:created.data.created_at,updatedAt:created.data.updated_at},value:created.data};}catch(error){providerError(error,"ref");}});}
    await workerTransaction(pool,async(client)=>{await client.query(`INSERT INTO git_pull_requests(id,workspace_id,project_id,repository_link_id,prepared_operation_id,provider_number,provider_node_id,html_url,head_branch,base_branch,title,state,provider_created_at,provider_updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(repository_link_id,provider_number) DO UPDATE SET provider_node_id=excluded.provider_node_id,html_url=excluded.html_url,head_branch=excluded.head_branch,base_branch=excluded.base_branch,title=excluded.title,state=excluded.state,provider_updated_at=excluded.provider_updated_at,updated_at=now()`,[newFolioId(),context.prepared.workspace_id,context.prepared.project_id,context.prepared.repository_link_id,context.prepared.id,pull.number,pull.node_id,pull.html_url,pull.head.ref,pull.base.ref,pull.title,pull.state==="open"?"open":"closed",pull.created_at,pull.updated_at]);});
    return finishSuccess(pool,context,{preparedOperationId:context.prepared.id,commitSha,targetBranch:context.prepared.target_branch,direct:false,pullRequest:{number:pull.number,url:pull.html_url,state:pull.state}});
  }catch(error){await markFailure(pool,context.prepared,error);throw error;}
}
