import type { Pool, PoolClient } from "pg";
import { postgresPool } from "@/db/postgres";
import { establishTenantContext } from "@/db/tenant";
import { getGitHubRef, GitHubProviderError } from "@/integrations/github/app-client";
import { newFolioId } from "@/lib/folio-ids";
import { authorizeEcosystemProjectCapability } from "@/services/ecosystem-access";
import { FoundationServiceError } from "@/services/foundation/errors";
import {
  findIdempotentResult,
  inTransaction,
  lockIdempotencyKey,
  recordMutation,
  requestDigest,
} from "@/services/foundation/internal";
import type { MutationContext, MutationResult } from "@/services/foundation/types";
import { validateBranchName, validateScopeRule } from "@/services/github-path-policy";

export type RepositoryLink = {
  id:string;workspaceId:string;projectId:string;repositoryId:string;displayName:string;
  fullName:string;defaultBranch:string;writePolicy:"disabled"|"pull_request_only"|"direct_allowed";
  includeRules:string[];excludeRules:string[];rulesVersion:number;parserVersion:string;
  state:"active"|"disabled"|"removed";revision:number;
  branches:SelectedGitBranch[];
};
export type SelectedGitBranch = {
  id:string;repositoryLinkId:string;branchName:string;state:"enabled"|"disabled"|"inaccessible";
  activeSnapshotId:string|null;lastObservedHeadOid:string|null;lastReconciledAt:string|null;revision:number;
};

type LinkRow={id:string;workspace_id:string;project_id:string;repository_id:string;display_name:string;write_policy:RepositoryLink["writePolicy"];include_rules:string[];exclude_rules:string[];rules_version:string;parser_version:string;state:RepositoryLink["state"];revision:string;full_name:string;default_branch:string;provider_installation_id:string;owner_login:string;repository_name:string;installation_state:string;repository_state:string};
type BranchRow={id:string;repository_link_id:string;branch_name:string;state:SelectedGitBranch["state"];active_snapshot_id:string|null;last_observed_head_oid:string|null;last_reconciled_at:Date|null;revision:string};
const linkColumns=`link.id,link.workspace_id,link.project_id,link.repository_id,link.display_name,link.write_policy,
  link.include_rules,link.exclude_rules,link.rules_version,link.parser_version,link.state,link.revision,
  repository.full_name,repository.default_branch,repository.owner_login,repository.name repository_name,
  installation.provider_installation_id,installation.state installation_state,repository.state repository_state`;
const branchColumns=`id,repository_link_id,branch_name,state,active_snapshot_id,last_observed_head_oid,last_reconciled_at,revision`;

function mapBranch(row:BranchRow):SelectedGitBranch{return{id:row.id,repositoryLinkId:row.repository_link_id,branchName:row.branch_name,state:row.state,activeSnapshotId:row.active_snapshot_id,lastObservedHeadOid:row.last_observed_head_oid,lastReconciledAt:row.last_reconciled_at?.toISOString()??null,revision:Number(row.revision)};}
function mapLink(row:LinkRow,branches:SelectedGitBranch[]):RepositoryLink{return{id:row.id,workspaceId:row.workspace_id,projectId:row.project_id,repositoryId:row.repository_id,displayName:row.display_name,fullName:row.full_name,defaultBranch:row.default_branch,writePolicy:row.write_policy,includeRules:row.include_rules,excludeRules:row.exclude_rules,rulesVersion:Number(row.rules_version),parserVersion:row.parser_version,state:row.state,revision:Number(row.revision),branches:branches.filter((branch)=>branch.repositoryLinkId===row.id)};}
function providerFailure(error:unknown):never{if(error instanceof GitHubProviderError){throw new FoundationServiceError(error.code==="GITHUB_NOT_FOUND"?"NOT_FOUND":error.code==="GITHUB_FORBIDDEN"||error.code==="GITHUB_UNAUTHORIZED"?"CAPABILITY_DENIED":"CONFLICT",error.message,{providerCode:error.code,retryable:error.retryable});}throw error;}
function displayName(value:string){const result=value.trim();if(!result||result.length>200)throw new FoundationServiceError("VALIDATION_FAILED","Repository link display name is invalid.");return result;}
function rules(values:string[]|undefined,fallback:string[]){const normalized=(values??fallback).map(validateScopeRule);if(!normalized.length||normalized.length>100)throw new FoundationServiceError("VALIDATION_FAILED","Markdown scope must contain 1 to 100 include rules.");return [...new Set(normalized)];}

async function readLink(client:PoolClient,input:{workspaceId:string;projectId:string;linkId:string},lock=false){const result=await client.query<LinkRow>(`SELECT ${linkColumns} FROM project_repository_links link JOIN github_repositories repository ON repository.workspace_id=link.workspace_id AND repository.id=link.repository_id JOIN github_app_installations installation ON installation.workspace_id=repository.workspace_id AND installation.id=repository.installation_id WHERE link.workspace_id=$1 AND link.project_id=$2 AND link.id=$3 ${lock?"FOR UPDATE OF link":""}`,[input.workspaceId,input.projectId,input.linkId]);if(!result.rows[0])throw new FoundationServiceError("NOT_FOUND","Project repository link was not found.");return result.rows[0];}

export async function listProjectRepositoryLinks(input:{workspaceId:string;projectId:string},principalId:string,pool:Pool=postgresPool()):Promise<RepositoryLink[]>{return inTransaction(pool,async(client)=>{await establishTenantContext(client,input.workspaceId,principalId);await authorizeEcosystemProjectCapability(client,{...input,principalId,capability:"repository.read"});const links=await client.query<LinkRow>(`SELECT ${linkColumns} FROM project_repository_links link JOIN github_repositories repository ON repository.workspace_id=link.workspace_id AND repository.id=link.repository_id JOIN github_app_installations installation ON installation.workspace_id=repository.workspace_id AND installation.id=repository.installation_id WHERE link.workspace_id=$1 AND link.project_id=$2 AND link.state<>'removed' ORDER BY link.updated_at DESC,link.id`,[input.workspaceId,input.projectId]);const branches=await client.query<BranchRow>(`SELECT ${branchColumns} FROM selected_git_branches WHERE workspace_id=$1 AND project_id=$2 ORDER BY branch_name,id`,[input.workspaceId,input.projectId]);const mapped=branches.rows.map(mapBranch);return links.rows.map((row)=>mapLink(row,mapped));});}

export async function createProjectRepositoryLink(
  raw:{workspaceId:string;projectId:string;repositoryId:string;displayName?:string;writePolicy?:RepositoryLink["writePolicy"];includeRules?:string[];excludeRules?:string[]},
  context:MutationContext,pool:Pool=postgresPool(),
):Promise<MutationResult<RepositoryLink>>{
  const includeRules=rules(raw.includeRules,["**/*.md","**/*.markdown"]);const excludeRules=(raw.excludeRules??[]).map(validateScopeRule);if(excludeRules.length>100)throw new FoundationServiceError("VALIDATION_FAILED","Markdown scope contains too many exclude rules.");
  const input={...raw,displayName:displayName(raw.displayName??"Repository"),writePolicy:raw.writePolicy??"pull_request_only",includeRules,excludeRules:[...new Set(excludeRules)]};const operation="github.repository_link.create";const digest=requestDigest(input);
  return inTransaction(pool,async(client)=>{await establishTenantContext(client,input.workspaceId,context.actorPrincipalId);await lockIdempotencyKey(client,context.actorPrincipalId,operation,context.idempotencyKey);const replay=await findIdempotentResult<RepositoryLink>(client,{workspaceId:input.workspaceId,projectId:input.projectId,principalId:context.actorPrincipalId,operation,key:context.idempotencyKey,digest});if(replay)return replay;await authorizeEcosystemProjectCapability(client,{workspaceId:input.workspaceId,projectId:input.projectId,principalId:context.actorPrincipalId,capability:"repository.manage"});const repository=await client.query<{full_name:string;default_branch:string;state:string;installation_state:string}>(`SELECT repository.full_name,repository.default_branch,repository.state,installation.state installation_state FROM github_repositories repository JOIN github_app_installations installation ON installation.workspace_id=repository.workspace_id AND installation.id=repository.installation_id WHERE repository.workspace_id=$1 AND repository.id=$2`,[input.workspaceId,input.repositoryId]);const repo=repository.rows[0];if(!repo||repo.state!=="available"||repo.installation_state!=="active")throw new FoundationServiceError("CONFLICT","GitHub repository is not currently available.");const id=newFolioId();let row;try{row=await client.query<LinkRow>(`INSERT INTO project_repository_links(id,workspace_id,project_id,repository_id,display_name,write_policy,include_rules,exclude_rules,created_by_principal_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,workspace_id,project_id,repository_id,display_name,write_policy,include_rules,exclude_rules,rules_version,parser_version,state,revision,$10::text full_name,$11::text default_branch,''::text provider_installation_id,''::text owner_login,''::text repository_name,''::text installation_state,''::text repository_state`,[id,input.workspaceId,input.projectId,input.repositoryId,input.displayName,input.writePolicy,input.includeRules,input.excludeRules,context.actorPrincipalId,repo.full_name,repo.default_branch]);}catch(error){if((error as {code?:string}).code==='23505')throw new FoundationServiceError("CONFLICT","Repository is already linked to this project.");throw error;}const data=mapLink(row.rows[0]!,[]);return recordMutation(client,{workspaceId:input.workspaceId,projectId:input.projectId,context,operation,digest,action:operation,targetType:"repository_link",targetId:id,aggregateType:"repository_link",aggregateRevision:1,eventType:"github.repository_link_created.v1",inputSummary:{writePolicy:input.writePolicy,includeRuleCount:input.includeRules.length,excludeRuleCount:input.excludeRules.length},resultSummary:{repositoryLinkId:id,fullName:repo.full_name},data});});
}

export async function updateProjectRepositoryLink(
  raw:{workspaceId:string;projectId:string;linkId:string;expectedRevision:number;displayName?:string;writePolicy?:RepositoryLink["writePolicy"];includeRules?:string[];excludeRules?:string[];state?:"active"|"disabled"},
  context:MutationContext,pool:Pool=postgresPool(),
):Promise<MutationResult<RepositoryLink>>{
  if(!Number.isSafeInteger(raw.expectedRevision)||raw.expectedRevision<1)throw new FoundationServiceError("VALIDATION_FAILED","Expected revision is invalid.");
  const input={...raw,displayName:raw.displayName===undefined?undefined:displayName(raw.displayName),includeRules:raw.includeRules===undefined?undefined:rules(raw.includeRules,[]),excludeRules:raw.excludeRules===undefined?undefined:[...new Set(raw.excludeRules.map(validateScopeRule))]};const operation="github.repository_link.update";const digest=requestDigest(input);
  return inTransaction(pool,async(client)=>{await establishTenantContext(client,input.workspaceId,context.actorPrincipalId);await lockIdempotencyKey(client,context.actorPrincipalId,operation,context.idempotencyKey);const replay=await findIdempotentResult<RepositoryLink>(client,{workspaceId:input.workspaceId,projectId:input.projectId,principalId:context.actorPrincipalId,operation,key:context.idempotencyKey,digest});if(replay)return replay;await authorizeEcosystemProjectCapability(client,{workspaceId:input.workspaceId,projectId:input.projectId,principalId:context.actorPrincipalId,capability:"repository.manage"});const current=await readLink(client,input,true);const rulesChanged=input.includeRules!==undefined||input.excludeRules!==undefined;const updated=await client.query<LinkRow>(`UPDATE project_repository_links link SET display_name=coalesce($5,display_name),write_policy=coalesce($6,write_policy),include_rules=coalesce($7,include_rules),exclude_rules=coalesce($8,exclude_rules),state=coalesce($9,state),rules_version=rules_version+CASE WHEN $10 THEN 1 ELSE 0 END,revision=revision+1,updated_at=now() FROM github_repositories repository,github_app_installations installation WHERE link.workspace_id=$1 AND link.project_id=$2 AND link.id=$3 AND link.revision=$4 AND repository.workspace_id=link.workspace_id AND repository.id=link.repository_id AND installation.workspace_id=repository.workspace_id AND installation.id=repository.installation_id RETURNING ${linkColumns}`,[input.workspaceId,input.projectId,input.linkId,input.expectedRevision,input.displayName??null,input.writePolicy??null,input.includeRules??null,input.excludeRules??null,input.state??null,rulesChanged]);if(!updated.rows[0])throw new FoundationServiceError("REVISION_CONFLICT","Repository link changed after it was read.",{expectedRevision:input.expectedRevision,currentRevision:Number(current.revision)});const branches=await client.query<BranchRow>(`SELECT ${branchColumns} FROM selected_git_branches WHERE repository_link_id=$1`,[input.linkId]);const data=mapLink(updated.rows[0],branches.rows.map(mapBranch));return recordMutation(client,{workspaceId:input.workspaceId,projectId:input.projectId,context,operation,digest,action:operation,targetType:"repository_link",targetId:input.linkId,aggregateType:"repository_link",aggregateRevision:data.revision,eventType:"github.repository_link_updated.v1",inputSummary:{rulesChanged,changedFields:Object.keys(raw).filter((key)=>!["workspaceId","projectId","linkId","expectedRevision"].includes(key))},resultSummary:{repositoryLinkId:data.id,revision:data.revision},data});});
}

export async function addSelectedGitBranch(
  raw:{workspaceId:string;projectId:string;linkId:string;branchName:string},context:MutationContext,pool:Pool=postgresPool(),
):Promise<MutationResult<SelectedGitBranch>>{
  const branchName=validateBranchName(raw.branchName);const input={...raw,branchName};const operation="github.branch.select";const digest=requestDigest(input);
  const link=await inTransaction(pool,async(client)=>{await establishTenantContext(client,input.workspaceId,context.actorPrincipalId);await authorizeEcosystemProjectCapability(client,{workspaceId:input.workspaceId,projectId:input.projectId,principalId:context.actorPrincipalId,capability:"repository.manage"});const value=await readLink(client,input);if(value.state!=="active"||value.repository_state!=="available"||value.installation_state!=="active")throw new FoundationServiceError("CONFLICT","Repository link is not available for branch selection.");return value;});
  let provider;try{provider=await getGitHubRef(Number(link.provider_installation_id),link.owner_login,link.repository_name,`heads/${branchName}`);}catch(error){providerFailure(error);}
  return inTransaction(pool,async(client)=>{await establishTenantContext(client,input.workspaceId,context.actorPrincipalId);await lockIdempotencyKey(client,context.actorPrincipalId,operation,context.idempotencyKey);const replay=await findIdempotentResult<SelectedGitBranch>(client,{workspaceId:input.workspaceId,projectId:input.projectId,principalId:context.actorPrincipalId,operation,key:context.idempotencyKey,digest});if(replay)return replay;await authorizeEcosystemProjectCapability(client,{workspaceId:input.workspaceId,projectId:input.projectId,principalId:context.actorPrincipalId,capability:"repository.manage"});const id=newFolioId();let result;try{result=await client.query<BranchRow>(`INSERT INTO selected_git_branches(id,workspace_id,project_id,repository_link_id,branch_name,last_observed_head_oid,created_by_principal_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING ${branchColumns}`,[id,input.workspaceId,input.projectId,input.linkId,branchName,provider.data.object.sha,context.actorPrincipalId]);}catch(error){if((error as {code?:string}).code==='23505')throw new FoundationServiceError("CONFLICT","Branch is already selected.");throw error;}await client.query(`INSERT INTO jobs(id,workspace_id,project_id,kind,payload,deduplication_key,status,priority,max_attempts,available_at) VALUES($1,$2,$3,'github.branch.reconcile',$4,$5,'pending',50,8,now()) ON CONFLICT DO NOTHING`,[newFolioId(),input.workspaceId,input.projectId,{selectedBranchId:id,headHint:provider.data.object.sha},`github-reconcile:${id}:${provider.data.object.sha}`]);const data=mapBranch(result.rows[0]!);return recordMutation(client,{workspaceId:input.workspaceId,projectId:input.projectId,context,operation,digest,action:operation,targetType:"selected_git_branch",targetId:id,aggregateType:"selected_git_branch",aggregateRevision:1,eventType:"github.branch_selected.v1",inputSummary:{branchName},resultSummary:{selectedBranchId:id,headOid:provider.data.object.sha},data});});
}

export async function requestGitBranchReconciliation(
  raw:{workspaceId:string;projectId:string;selectedBranchId:string},context:MutationContext,pool:Pool=postgresPool(),
):Promise<MutationResult<{jobId:string;selectedBranchId:string}>>{
  const operation="github.branch.reconcile.request";const digest=requestDigest(raw);
  return inTransaction(pool,async(client)=>{await establishTenantContext(client,raw.workspaceId,context.actorPrincipalId);await lockIdempotencyKey(client,context.actorPrincipalId,operation,context.idempotencyKey);const replay=await findIdempotentResult<{jobId:string;selectedBranchId:string}>(client,{workspaceId:raw.workspaceId,projectId:raw.projectId,principalId:context.actorPrincipalId,operation,key:context.idempotencyKey,digest});if(replay)return replay;await authorizeEcosystemProjectCapability(client,{workspaceId:raw.workspaceId,projectId:raw.projectId,principalId:context.actorPrincipalId,capability:"repository.reconcile"});const branch=await client.query<{id:string}>(`SELECT id FROM selected_git_branches WHERE workspace_id=$1 AND project_id=$2 AND id=$3 AND state='enabled'`,[raw.workspaceId,raw.projectId,raw.selectedBranchId]);if(!branch.rows[0])throw new FoundationServiceError("NOT_FOUND","Selected branch was not found.");const jobId=newFolioId();await client.query(`INSERT INTO jobs(id,workspace_id,project_id,kind,payload,deduplication_key,status,priority,max_attempts,available_at) VALUES($1,$2,$3,'github.branch.reconcile',$4,$5,'pending',50,8,now()) ON CONFLICT DO NOTHING`,[jobId,raw.workspaceId,raw.projectId,{selectedBranchId:raw.selectedBranchId},`github-reconcile:${raw.selectedBranchId}:manual`]);const data={jobId,selectedBranchId:raw.selectedBranchId};return recordMutation(client,{workspaceId:raw.workspaceId,projectId:raw.projectId,context,operation,digest,action:operation,targetType:"selected_git_branch",targetId:raw.selectedBranchId,aggregateType:"selected_git_branch",aggregateRevision:1,eventType:"github.branch_reconciliation_requested.v1",inputSummary:{manual:true},resultSummary:data,data});});
}
