import type { Pool } from "pg";
import { postgresPool } from "@/db/postgres";
import { establishTenantContext } from "@/db/tenant";
import { newFolioId } from "@/lib/folio-ids";
import { applyCanvasCommand, readCanvas, type CanvasElementKind } from "@/services/canvas-scenes";
import { authorizeOwnedEcosystemObject, readCanvasPolicy } from "@/services/ecosystem-access";
import { FoundationServiceError } from "@/services/foundation/errors";
import { inTransaction } from "@/services/foundation/internal";
import type { MutationContext } from "@/services/foundation/types";

export type MermaidPreview={id:string;direction:"import"|"export";canvasId:string|null;sourceText:string|null;candidateScene:Record<string,unknown>|null;warnings:string[];losses:string[];baseCanvasRevision:number|null;expiresAt:string;consumedAt:string|null};
type PreviewRow={id:string;direction:MermaidPreview["direction"];canvas_id:string|null;source_text:string|null;candidate_scene:Record<string,unknown>|null;warnings:string[];losses:string[];base_canvas_revision:string|null;expires_at:Date;consumed_at:Date|null};
const columns=`id,direction,canvas_id,source_text,candidate_scene,warnings,losses,base_canvas_revision,expires_at,consumed_at`;
const map=(row:PreviewRow):MermaidPreview=>({id:row.id,direction:row.direction,canvasId:row.canvas_id,sourceText:row.source_text,candidateScene:row.candidate_scene,warnings:row.warnings,losses:row.losses,baseCanvasRevision:row.base_canvas_revision===null?null:Number(row.base_canvas_revision),expiresAt:row.expires_at.toISOString(),consumedAt:row.consumed_at?.toISOString()??null});
function cleanLabel(value:string){return value.replaceAll('\\n',' ').replace(/["\[\]{}]/g,'').trim().slice(0,240)||"Untitled";}
function parseMermaid(source:string){if(Buffer.byteLength(source)>200*1024)throw new FoundationServiceError("VALIDATION_FAILED","Mermaid source must be at most 200 KiB.");const lines=source.split(/\r?\n/).map((line)=>line.trim()).filter(Boolean);if(!lines.length||!/^flowchart\s+(TD|TB|LR|RL|BT)$/i.test(lines[0]!))throw new FoundationServiceError("VALIDATION_FAILED","Only Mermaid flowchart syntax is supported.");const nodes=new Map<string,{id:string;label:string}>();const edges:Array<{from:string;to:string;label:string|null}>=[];const warnings:string[]=[];const losses:string[]=[];const nodePattern=/^([A-Za-z][A-Za-z0-9_-]{0,79})\s*(?:\["?([^\]"]+)"?\]|\("?([^\)"]+)"?\)|\{"?([^\}"]+)"?\})?$/;const edgePattern=/^(.+?)\s*(-->|---|-.->|==>)\s*(?:\|([^|]{0,120})\|\s*)?(.+)$/;const ensureNode=(token:string)=>{const match=nodePattern.exec(token.trim());if(!match)return null;const id=match[1]!;const label=cleanLabel(match[2]??match[3]??match[4]??id);if(!nodes.has(id))nodes.set(id,{id,label});return id;};for(const line of lines.slice(1)){if(line.startsWith("%%"))continue;const edge=edgePattern.exec(line);if(edge){const from=ensureNode(edge[1]!);const to=ensureNode(edge[4]!);if(!from||!to){warnings.push(`Skipped unsupported edge: ${line.slice(0,160)}`);continue;}edges.push({from,to,label:edge[3]?.trim()||null});if(edge[2]!=="-->")losses.push(`Edge style ${edge[2]} will import as a standard connector.`);continue;}if(ensureNode(line))continue;if(/^(subgraph|end|classDef|class|style|click|linkStyle)\b/i.test(line)){warnings.push(`Skipped unsupported directive: ${line.slice(0,160)}`);continue;}warnings.push(`Skipped unsupported Mermaid line: ${line.slice(0,160)}`);}if(nodes.size>1000||edges.length>2000)throw new FoundationServiceError("VALIDATION_FAILED","Mermaid diagram exceeds the supported node or edge limit.");const elementIds=new Map<string,string>();const elements:Array<{id:string;kind:CanvasElementKind;geometry:Record<string,unknown>;content:Record<string,unknown>;zIndex:number}>=[];let index=0;for(const node of nodes.values()){const id=newFolioId();elementIds.set(node.id,id);const column=index%8;const row=Math.floor(index/8);elements.push({id,kind:"text",geometry:{x:column*220,y:row*140,width:180,height:80},content:{text:node.label,mermaidId:node.id},zIndex:index});index++;}for(const edge of edges){elements.push({id:newFolioId(),kind:"connector",geometry:{},content:{fromElementId:elementIds.get(edge.from),toElementId:elementIds.get(edge.to),label:edge.label},zIndex:index++});}return{scene:{sceneVersion:1,elements},warnings:[...new Set(warnings)].slice(0,200),losses:[...new Set(losses)].slice(0,200)};}

export async function previewMermaidImport(input:{workspaceId:string;projectId:string;canvasId:string;sourceText:string},principalId:string,pool:Pool=postgresPool()):Promise<MermaidPreview>{const parsed=parseMermaid(input.sourceText);return inTransaction(pool,async(client)=>{await establishTenantContext(client,input.workspaceId,principalId);const policy=await readCanvasPolicy(client,input);await authorizeOwnedEcosystemObject(client,{workspaceId:input.workspaceId,projectId:input.projectId,principalId,capability:"canvas.edit",objectType:"canvas",objectId:input.canvasId,ownerPrincipalId:policy.ownerPrincipalId,visibility:policy.visibility});const id=newFolioId();const result=await client.query<PreviewRow>(`INSERT INTO mermaid_interchange_previews(id,workspace_id,project_id,canvas_id,direction,source_text,candidate_scene,warnings,losses,base_canvas_revision,created_by_principal_id,expires_at) VALUES($1,$2,$3,$4,'import',$5,$6,$7,$8,$9,$10,now()+interval '15 minutes') RETURNING ${columns}`,[id,input.workspaceId,input.projectId,input.canvasId,input.sourceText,parsed.scene,parsed.warnings,parsed.losses,policy.revision,principalId]);return map(result.rows[0]!);});}

function nodeId(index:number){return `N${index+1}`;}
export async function previewMermaidExport(input:{workspaceId:string;projectId:string;canvasId:string},principalId:string,pool:Pool=postgresPool()):Promise<MermaidPreview>{const canvas=await readCanvas(input,principalId,pool);const exportable=canvas.elements.filter((element)=>['entity_card','sticky','text','shape','mermaid'].includes(element.kind));const ids=new Map(exportable.map((element,index)=>[element.id,nodeId(index)]));const lines=["flowchart LR"];const losses:string[]=[];for(const element of exportable){const label=element.kind==="entity_card"?`${element.entityType}:${element.entityId}`:typeof element.content.text==="string"?element.content.text:typeof element.content.title==="string"?element.content.title:element.kind;lines.push(`${ids.get(element.id)}["${cleanLabel(label)}"]`);}for(const connector of canvas.elements.filter((element)=>element.kind==="connector")){const from=typeof connector.content.fromElementId==="string"?ids.get(connector.content.fromElementId):null;const to=typeof connector.content.toElementId==="string"?ids.get(connector.content.toElementId):null;if(from&&to)lines.push(`${from} --> ${to}`);}const unsupported=canvas.elements.filter((element)=>!['entity_card','sticky','text','shape','mermaid','connector'].includes(element.kind));if(unsupported.length)losses.push(`${unsupported.length} unsupported Canvas elements are omitted from Mermaid export.`);const sourceText=lines.join("\n");return inTransaction(pool,async(client)=>{await establishTenantContext(client,input.workspaceId,principalId);const id=newFolioId();const result=await client.query<PreviewRow>(`INSERT INTO mermaid_interchange_previews(id,workspace_id,project_id,canvas_id,direction,source_text,warnings,losses,base_canvas_revision,created_by_principal_id,expires_at) VALUES($1,$2,$3,$4,'export',$5,'[]'::jsonb,$6,$7,$8,now()+interval '15 minutes') RETURNING ${columns}`,[id,input.workspaceId,input.projectId,input.canvasId,sourceText,losses,canvas.revision,principalId]);return map(result.rows[0]!);});}

export async function executeMermaidImport(input:{workspaceId:string;projectId:string;previewId:string;clientId:string},context:MutationContext,pool:Pool=postgresPool()):Promise<{canvasId:string;revision:number;createdElementIds:string[]}>{const preview=await inTransaction(pool,async(client)=>{await establishTenantContext(client,input.workspaceId,context.actorPrincipalId);const result=await client.query<PreviewRow>(`SELECT ${columns} FROM mermaid_interchange_previews WHERE workspace_id=$1 AND project_id=$2 AND id=$3 AND direction='import' AND consumed_at IS NULL AND expires_at>now() FOR UPDATE`,[input.workspaceId,input.projectId,input.previewId]);const row=result.rows[0];if(!row||!row.canvas_id||!row.candidate_scene)throw new FoundationServiceError("NOT_FOUND","Active Mermaid import preview was not found.");const policy=await readCanvasPolicy(client,{workspaceId:input.workspaceId,projectId:input.projectId,canvasId:row.canvas_id});await authorizeOwnedEcosystemObject(client,{workspaceId:input.workspaceId,projectId:input.projectId,principalId:context.actorPrincipalId,capability:"canvas.edit",objectType:"canvas",objectId:row.canvas_id,ownerPrincipalId:policy.ownerPrincipalId,visibility:policy.visibility});if(policy.revision!==Number(row.base_canvas_revision))throw new FoundationServiceError("REVISION_CONFLICT","Canvas changed after the Mermaid preview was created.",{expectedRevision:Number(row.base_canvas_revision),currentRevision:policy.revision});return row;});const elements=Array.isArray(preview.candidate_scene.elements)?preview.candidate_scene.elements as Array<Record<string,unknown>>:[];let revision=Number(preview.base_canvas_revision);const createdElementIds:string[]=[];let clientSequence=1;for(const element of elements){const id=typeof element.id==="string"?element.id:newFolioId();const result=await applyCanvasCommand({workspaceId:input.workspaceId,projectId:input.projectId,canvasId:preview.canvas_id!,expectedRevision:revision,clientId:input.clientId,clientSequence,command:{type:"element.create",element:{id,kind:element.kind as CanvasElementKind,geometry:element.geometry as Record<string,unknown>,content:element.content as Record<string,unknown>,zIndex:typeof element.zIndex==="number"?element.zIndex:clientSequence}}},{...context,idempotencyKey:`${context.idempotencyKey}:${clientSequence}`},pool);revision=result.data.revision;createdElementIds.push(id);clientSequence++;}await inTransaction(pool,async(client)=>{await establishTenantContext(client,input.workspaceId,context.actorPrincipalId);await client.query(`UPDATE mermaid_interchange_previews SET consumed_at=now() WHERE workspace_id=$1 AND project_id=$2 AND id=$3 AND consumed_at IS NULL`,[input.workspaceId,input.projectId,input.previewId]);});return{canvasId:preview.canvas_id!,revision,createdElementIds};}
