import type { Pool, PoolClient } from "pg";
import { postgresPool } from "@/db/postgres";
import { establishTenantContext } from "@/db/tenant";
import { newFolioId } from "@/lib/folio-ids";
import { FoundationServiceError } from "@/services/foundation/errors";
import {
  findIdempotentResult,
  inTransaction,
  lockIdempotencyKey,
  recordMutation,
  requestDigest,
} from "@/services/foundation/internal";
import type { MutationContext, MutationResult } from "@/services/foundation/types";
import { authorizeScheduleObject, readCalendarPolicy, readTodoListPolicy } from "@/services/schedule-access";

export type Reminder = {
  id: string;
  todoId: string | null;
  calendarEntryId: string | null;
  recipientPrincipalId: string;
  remindAt: string;
  state: "pending" | "leased" | "sent" | "failed" | "canceled";
  deliveryChannel: "in_app" | "email" | "provider";
  deduplicationKey: string;
  attemptCount: number;
  maxAttempts: number;
  availableAt: string;
  leasedUntil: string | null;
  leasedBy: string | null;
  lastErrorCode: string | null;
  lastErrorMessage: string | null;
  sentAt: string | null;
  createdAt: string;
  updatedAt: string;
};

type ReminderRow = {
  id:string;todo_id:string|null;calendar_entry_id:string|null;recipient_principal_id:string;
  remind_at:Date;state:Reminder["state"];delivery_channel:Reminder["deliveryChannel"];
  deduplication_key:string;attempt_count:number;max_attempts:number;available_at:Date;
  leased_until:Date|null;leased_by:string|null;last_error_code:string|null;last_error_message:string|null;
  sent_at:Date|null;created_at:Date;updated_at:Date;
};
const columns=`id,todo_id,calendar_entry_id,recipient_principal_id,remind_at,state,delivery_channel,deduplication_key,attempt_count,max_attempts,available_at,leased_until,leased_by,last_error_code,last_error_message,sent_at,created_at,updated_at`;
function map(row:ReminderRow):Reminder{return{id:row.id,todoId:row.todo_id,calendarEntryId:row.calendar_entry_id,recipientPrincipalId:row.recipient_principal_id,remindAt:row.remind_at.toISOString(),state:row.state,deliveryChannel:row.delivery_channel,deduplicationKey:row.deduplication_key,attemptCount:Number(row.attempt_count),maxAttempts:Number(row.max_attempts),availableAt:row.available_at.toISOString(),leasedUntil:row.leased_until?.toISOString()??null,leasedBy:row.leased_by,lastErrorCode:row.last_error_code,lastErrorMessage:row.last_error_message,sentAt:row.sent_at?.toISOString()??null,createdAt:row.created_at.toISOString(),updatedAt:row.updated_at.toISOString()};}
function instant(value:string,label:string){const result=new Date(value);if(Number.isNaN(result.getTime()))throw new FoundationServiceError("VALIDATION_FAILED",`${label} must be an ISO date-time.`);return result.toISOString();}
function boundedKey(value:string){const key=value.trim();if(!key||key.length>240)throw new FoundationServiceError("VALIDATION_FAILED","Reminder deduplication key must contain 1 to 240 characters.");return key;}

async function authorizeReminderTarget(client:PoolClient,input:{workspaceId:string;projectId:string;principalId:string;todoId?:string|null;calendarEntryId?:string|null;capability:"read"|"edit"}){
  if(Boolean(input.todoId)===Boolean(input.calendarEntryId))throw new FoundationServiceError("VALIDATION_FAILED","Reminder requires exactly one target.");
  if(input.todoId){const result=await client.query<{list_id:string}>(`SELECT list_id FROM todos WHERE workspace_id=$1 AND project_id=$2 AND id=$3 AND archived_at IS NULL`,[input.workspaceId,input.projectId,input.todoId]);const row=result.rows[0];if(!row)throw new FoundationServiceError("NOT_FOUND","To-do was not found.");const policy=await readTodoListPolicy(client,{workspaceId:input.workspaceId,projectId:input.projectId,listId:row.list_id});await authorizeScheduleObject(client,{workspaceId:input.workspaceId,projectId:input.projectId,principalId:input.principalId,capability:input.capability==="read"?"todo.read":"todo.edit",objectType:"todo_list",objectId:row.list_id,ownerPrincipalId:policy.ownerPrincipalId,visibility:policy.visibility});return;}
  const result=await client.query<{calendar_id:string}>(`SELECT calendar_id FROM calendar_entries WHERE workspace_id=$1 AND project_id=$2 AND id=$3 AND archived_at IS NULL`,[input.workspaceId,input.projectId,input.calendarEntryId]);const row=result.rows[0];if(!row)throw new FoundationServiceError("NOT_FOUND","Calendar entry was not found.");const policy=await readCalendarPolicy(client,{workspaceId:input.workspaceId,projectId:input.projectId,calendarId:row.calendar_id});await authorizeScheduleObject(client,{workspaceId:input.workspaceId,projectId:input.projectId,principalId:input.principalId,capability:input.capability==="read"?"calendar.read":"calendar.edit",objectType:"calendar",objectId:row.calendar_id,ownerPrincipalId:policy.ownerPrincipalId,visibility:policy.visibility});
}

export async function createReminder(raw:{workspaceId:string;projectId:string;todoId?:string|null;calendarEntryId?:string|null;recipientPrincipalId:string;remindAt:string;deliveryChannel?:Reminder["deliveryChannel"];deduplicationKey:string;maxAttempts?:number},context:MutationContext,pool:Pool=postgresPool()):Promise<MutationResult<Reminder>>{
  const maxAttempts=raw.maxAttempts??5;if(!Number.isSafeInteger(maxAttempts)||maxAttempts<1||maxAttempts>100)throw new FoundationServiceError("VALIDATION_FAILED","Reminder attempts must be between 1 and 100.");const input={...raw,todoId:raw.todoId??null,calendarEntryId:raw.calendarEntryId??null,remindAt:instant(raw.remindAt,"Reminder time"),deliveryChannel:raw.deliveryChannel??"in_app",deduplicationKey:boundedKey(raw.deduplicationKey),maxAttempts};const operation="reminder.create";const digest=requestDigest(input);
  return inTransaction(pool,async(client)=>{await establishTenantContext(client,input.workspaceId,context.actorPrincipalId);await lockIdempotencyKey(client,context.actorPrincipalId,operation,context.idempotencyKey);const replay=await findIdempotentResult<Reminder>(client,{workspaceId:input.workspaceId,projectId:input.projectId,principalId:context.actorPrincipalId,operation,key:context.idempotencyKey,digest});if(replay)return replay;await authorizeReminderTarget(client,{...input,principalId:context.actorPrincipalId,capability:"edit"});const recipient=await client.query(`SELECT 1 FROM project_memberships pm JOIN principals p ON p.id=pm.principal_id WHERE pm.workspace_id=$1 AND pm.project_id=$2 AND pm.principal_id=$3 AND pm.status='active' AND p.status='active'`,[input.workspaceId,input.projectId,input.recipientPrincipalId]);if(!recipient.rows[0])throw new FoundationServiceError("VALIDATION_FAILED","Reminder recipient must be an active project principal.");const id=newFolioId();const result=await client.query<ReminderRow>(`INSERT INTO reminders(id,workspace_id,project_id,todo_id,calendar_entry_id,recipient_principal_id,remind_at,delivery_channel,deduplication_key,max_attempts,available_at,created_by_principal_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$7,$11) RETURNING ${columns}`,[id,input.workspaceId,input.projectId,input.todoId,input.calendarEntryId,input.recipientPrincipalId,input.remindAt,input.deliveryChannel,input.deduplicationKey,input.maxAttempts,context.actorPrincipalId]);await client.query(`INSERT INTO jobs(id,workspace_id,project_id,kind,payload,deduplication_key,status,available_at) VALUES($1,$2,$3,'reminder.delivery',$4,$5,'pending',$6) ON CONFLICT DO NOTHING`,[newFolioId(),input.workspaceId,input.projectId,{reminderId:id},`reminder:${id}`,input.remindAt]);const data=map(result.rows[0]!);return recordMutation(client,{workspaceId:input.workspaceId,projectId:input.projectId,context,operation,digest,action:operation,targetType:"reminder",targetId:id,aggregateType:"reminder",aggregateRevision:1,eventType:"reminder.created.v1",inputSummary:{targetType:input.todoId?"todo":"calendar_entry",recipientPrincipalId:input.recipientPrincipalId,deliveryChannel:input.deliveryChannel},resultSummary:{reminderId:id,remindAt:input.remindAt},data});});
}

export async function listMyReminders(input:{workspaceId:string;projectId:string;includeTerminal?:boolean},principalId:string,pool:Pool=postgresPool()):Promise<Reminder[]>{return inTransaction(pool,async(client)=>{await establishTenantContext(client,input.workspaceId,principalId);const result=await client.query<ReminderRow>(`SELECT ${columns} FROM reminders WHERE workspace_id=$1 AND project_id=$2 AND recipient_principal_id=$3 AND ($4::boolean OR state IN ('pending','leased','failed')) ORDER BY remind_at,id`,[input.workspaceId,input.projectId,principalId,input.includeTerminal??false]);return result.rows.map(map);});}

export async function cancelReminder(raw:{workspaceId:string;projectId:string;reminderId:string},context:MutationContext,pool:Pool=postgresPool()):Promise<MutationResult<Reminder>>{const operation="reminder.cancel";const digest=requestDigest(raw);return inTransaction(pool,async(client)=>{await establishTenantContext(client,raw.workspaceId,context.actorPrincipalId);await lockIdempotencyKey(client,context.actorPrincipalId,operation,context.idempotencyKey);const replay=await findIdempotentResult<Reminder>(client,{workspaceId:raw.workspaceId,projectId:raw.projectId,principalId:context.actorPrincipalId,operation,key:context.idempotencyKey,digest});if(replay)return replay;const current=await client.query<ReminderRow>(`SELECT ${columns} FROM reminders WHERE workspace_id=$1 AND project_id=$2 AND id=$3`,[raw.workspaceId,raw.projectId,raw.reminderId]);const row=current.rows[0];if(!row)throw new FoundationServiceError("NOT_FOUND","Reminder was not found.");if(row.recipient_principal_id!==context.actorPrincipalId)await authorizeReminderTarget(client,{workspaceId:raw.workspaceId,projectId:raw.projectId,principalId:context.actorPrincipalId,todoId:row.todo_id,calendarEntryId:row.calendar_entry_id,capability:"edit"});const result=await client.query<ReminderRow>(`UPDATE reminders SET state='canceled',leased_until=NULL,leased_by=NULL,updated_at=now() WHERE workspace_id=$1 AND project_id=$2 AND id=$3 AND state IN ('pending','leased','failed') RETURNING ${columns}`,[raw.workspaceId,raw.projectId,raw.reminderId]);if(!result.rows[0])throw new FoundationServiceError("CONFLICT","Reminder can no longer be canceled.");const data=map(result.rows[0]);return recordMutation(client,{workspaceId:raw.workspaceId,projectId:raw.projectId,context,operation,digest,action:operation,targetType:"reminder",targetId:raw.reminderId,aggregateType:"reminder",aggregateRevision:data.attemptCount+1,eventType:"reminder.canceled.v1",inputSummary:{},resultSummary:{reminderId:data.id},data});});}

export async function claimDueReminders(input:{workspaceId:string;workerId:string;leaseSeconds?:number;limit?:number},pool:Pool=postgresPool()):Promise<Reminder[]>{const leaseSeconds=Math.max(5,Math.min(input.leaseSeconds??60,3600));const limit=Math.max(1,Math.min(input.limit??20,100));return inTransaction(pool,async(client)=>{await establishTenantContext(client,input.workspaceId,newFolioId());const result=await client.query<ReminderRow>(`WITH candidates AS (SELECT id FROM reminders WHERE workspace_id=$1 AND available_at<=now() AND remind_at<=now() AND (state='pending' OR state='failed' OR (state='leased' AND leased_until<now())) AND attempt_count<max_attempts ORDER BY available_at,remind_at,created_at FOR UPDATE SKIP LOCKED LIMIT $2), claimed AS (UPDATE reminders r SET state='leased',attempt_count=attempt_count+1,leased_by=$3,leased_until=now()+make_interval(secs=>$4),updated_at=now() FROM candidates c WHERE r.id=c.id RETURNING r.*) SELECT ${columns} FROM claimed`,[input.workspaceId,limit,input.workerId,leaseSeconds]);return result.rows.map(map);});}

export async function finishReminderAttempt(input:{workspaceId:string;reminderId:string;workerId:string;success:boolean;errorCode?:string;errorMessage?:string},pool:Pool=postgresPool()):Promise<Reminder>{return inTransaction(pool,async(client)=>{await establishTenantContext(client,input.workspaceId,newFolioId());const current=await client.query<ReminderRow>(`SELECT ${columns} FROM reminders WHERE workspace_id=$1 AND id=$2 FOR UPDATE`,[input.workspaceId,input.reminderId]);const row=current.rows[0];if(!row)throw new FoundationServiceError("NOT_FOUND","Reminder was not found.");if(row.state!=="leased"||row.leased_by!==input.workerId)throw new FoundationServiceError("CONFLICT","Reminder lease is not owned by this worker.");const terminal=!input.success&&row.attempt_count>=row.max_attempts;const backoffSeconds=Math.min(3600,Math.max(30,2**Math.min(row.attempt_count,10)*15));const result=await client.query<ReminderRow>(`UPDATE reminders SET state=CASE WHEN $4::boolean THEN 'sent' WHEN $5::boolean THEN 'failed' ELSE 'failed' END,sent_at=CASE WHEN $4::boolean THEN now() ELSE NULL END,available_at=CASE WHEN $4::boolean OR $5::boolean THEN available_at ELSE now()+make_interval(secs=>$6) END,leased_until=NULL,leased_by=NULL,last_error_code=CASE WHEN $4::boolean THEN NULL ELSE $7 END,last_error_message=CASE WHEN $4::boolean THEN NULL ELSE left($8,500) END,updated_at=now() WHERE workspace_id=$1 AND id=$2 AND leased_by=$3 RETURNING ${columns}`,[input.workspaceId,input.reminderId,input.workerId,input.success,terminal,backoffSeconds,input.errorCode??"DELIVERY_FAILED",input.errorMessage??"Reminder delivery failed"]);const data=map(result.rows[0]!);await client.query(`INSERT INTO operation_metrics(id,workspace_id,project_id,metric_name,metric_value,dimensions) VALUES($1,$2,(SELECT project_id FROM reminders WHERE id=$3),$4,1,$5)`,[newFolioId(),input.workspaceId,input.reminderId,input.success?"reminder.delivery.succeeded":"reminder.delivery.failed",{attempt:data.attemptCount,terminal}]);return data;});}
