import { z } from "zod";
import { authenticatedRequest, jsonError, jsonSuccess, requestContext } from "@/api";
import { FoundationServiceError } from "@/services/foundation";
import { createSavedGraphView } from "@/services/graph-explorer";
import { listPermissionFilteredGraphViews } from "@/services/graph-view-policy";
import { ecosystemMutationContext, ecosystemServiceError, mutationEnvelope } from "../ecosystem/response";

const entity=z.enum(["page","issue","todo","calendar_entry","canvas"]);
const scope=z.object({workspace_id:z.string().uuid(),project_id:z.string().uuid()}).strict();
const schema=scope.extend({name:z.string().trim().min(1).max(120),visibility:z.enum(["private","project"]).optional(),root_entities:z.array(z.object({type:entity,id:z.string().uuid()}).strict()).min(1).max(50),filters:z.record(z.unknown()).optional(),traversal:z.record(z.unknown()).optional(),layout:z.record(z.unknown()).optional()}).strict();
export const dynamic="force-dynamic";
export async function GET(request:Request){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;try{const url=new URL(request.url);const input=scope.parse({workspace_id:url.searchParams.get("workspace_id"),project_id:url.searchParams.get("project_id")});return jsonSuccess(await listPermissionFilteredGraphViews({workspaceId:input.workspace_id,projectId:input.project_id},authenticated.session.principalId),context);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);if(error instanceof FoundationServiceError)return ecosystemServiceError(error,context);return jsonError("OPERATION_FAILED",context,500);}}
export async function POST(request:Request){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;const key=request.headers.get("idempotency-key")?.trim();if(!key)return jsonError("VALIDATION_FAILED",context,400);try{const input=schema.parse(await request.json());const result=await createSavedGraphView({workspaceId:input.workspace_id,projectId:input.project_id,name:input.name,visibility:input.visibility,rootEntities:input.root_entities,filters:input.filters,traversal:input.traversal,layout:input.layout},ecosystemMutationContext(authenticated.session.principalId,context,key));return jsonSuccess(mutationEnvelope("graph_view",result),context,result.replayed?200:201);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);if(error instanceof FoundationServiceError)return ecosystemServiceError(error,context);return jsonError("OPERATION_FAILED",context,500);}}
