import { z } from "zod";
import { authenticatedRequest, jsonError, jsonSuccess, requestContext } from "@/api";
import { FoundationServiceError } from "@/services/foundation";
import { createWorkspaceIdentityConfig, listWorkspaceIdentityConfigs } from "@/services/enterprise-controls";
import { ecosystemMutationContext, ecosystemServiceError, mutationEnvelope } from "../../ecosystem/response";

const workspace=z.object({workspace_id:z.string().uuid()}).strict();
const create=workspace.extend({provider_kind:z.enum(["oidc","saml"]),display_name:z.string().trim().min(1).max(120),issuer:z.string().url(),secret_reference:z.string().min(1).max(500),allowed_domains:z.array(z.string()).max(100).optional(),attribute_mapping:z.record(z.unknown()).optional()}).strict();
export const dynamic="force-dynamic";
export async function GET(request:Request){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;try{const url=new URL(request.url);const input=workspace.parse({workspace_id:url.searchParams.get("workspace_id")});return jsonSuccess(await listWorkspaceIdentityConfigs(input.workspace_id,authenticated.session.principalId),context);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);if(error instanceof FoundationServiceError)return ecosystemServiceError(error,context);return jsonError("OPERATION_FAILED",context,500);}}
export async function POST(request:Request){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;const key=request.headers.get("idempotency-key")?.trim();if(!key)return jsonError("VALIDATION_FAILED",context,400);try{const input=create.parse(await request.json());const result=await createWorkspaceIdentityConfig({workspaceId:input.workspace_id,providerKind:input.provider_kind,displayName:input.display_name,issuer:input.issuer,secretReference:input.secret_reference,allowedDomains:input.allowed_domains,attributeMapping:input.attribute_mapping},ecosystemMutationContext(authenticated.session.principalId,context,key));return jsonSuccess(mutationEnvelope("identity",result),context,result.replayed?200:201);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);if(error instanceof FoundationServiceError)return ecosystemServiceError(error,context);return jsonError("OPERATION_FAILED",context,500);}}
