import { timingSafeEqual } from "node:crypto";
import { postgresPool } from "@/db/postgres";
import { env, folioDatabaseConfigured } from "@/lib/env";

export const dynamic="force-dynamic";

function authorized(request:Request){const configured=env.METRICS_BEARER_TOKEN;if(!configured)return false;const supplied=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"")??"";const left=Buffer.from(configured);const right=Buffer.from(supplied);return left.length===right.length&&timingSafeEqual(left,right);}
const metric=(name:string,value:number,help:string)=>`# HELP ${name} ${help}\n# TYPE ${name} gauge\n${name} ${Number.isFinite(value)?value:0}\n`;

export async function GET(request:Request){if(!authorized(request))return new Response("Not found\n",{status:404,headers:{"cache-control":"no-store"}});if(!folioDatabaseConfigured())return new Response(metric("folio_database_configured",0,"Whether PostgreSQL is configured."),{headers:{"content-type":"text/plain; version=0.0.4","cache-control":"no-store"}});const pool=postgresPool();const [jobs,webhooks,snapshots,writes,reminders]=await Promise.all([pool.query<{status:string;count:string}>(`SELECT status,count(*) count FROM jobs GROUP BY status`),pool.query<{status:string;count:string}>(`SELECT status,count(*) count FROM github_webhook_deliveries GROUP BY status`),pool.query<{state:string;count:string}>(`SELECT state,count(*) count FROM git_snapshots GROUP BY state`),pool.query<{state:string;count:string}>(`SELECT state,count(*) count FROM prepared_git_operations GROUP BY state`),pool.query<{state:string;count:string}>(`SELECT state,count(*) count FROM reminders GROUP BY state`)]);let body=metric("folio_database_configured",1,"Whether PostgreSQL is configured.");for(const row of jobs.rows)body+=metric(`folio_jobs_${row.status}`,Number(row.count),`Durable jobs in ${row.status} state.`);for(const row of webhooks.rows)body+=metric(`folio_github_webhooks_${row.status}`,Number(row.count),`GitHub webhook deliveries in ${row.status} state.`);for(const row of snapshots.rows)body+=metric(`folio_git_snapshots_${row.state}`,Number(row.count),`Git snapshots in ${row.state} state.`);for(const row of writes.rows)body+=metric(`folio_git_writes_${row.state}`,Number(row.count),`Prepared Git writes in ${row.state} state.`);for(const row of reminders.rows)body+=metric(`folio_reminders_${row.state}`,Number(row.count),`Reminders in ${row.state} state.`);return new Response(body,{headers:{"content-type":"text/plain; version=0.0.4","cache-control":"no-store"}});}
