import { z } from "zod";
import { authenticatedRequest, jsonError, jsonSuccess, requestContext } from "@/api";
import { FoundationServiceError } from "@/services/foundation";
import { createScaleDecision, listScaleDecisions, listScaleMeasurements, recordScaleMeasurement } from "@/services/scale-governance";
import { ecosystemMutationContext, ecosystemServiceError, mutationEnvelope } from "../ecosystem/response";

const component=z.enum(["search","queue","realtime","database","object_storage"]);
const scope=z.object({workspace_id:z.string().uuid(),project_id:z.string().uuid()}).strict();
const measurement=scope.extend({kind:z.literal("measurement"),component,metric_name:z.string(),window_start:z.string(),window_end:z.string(),sample_count:z.number().int().nonnegative(),p50:z.number().nonnegative().nullable().optional(),p95:z.number().nonnegative().nullable().optional(),p99:z.number().nonnegative().nullable().optional(),maximum:z.number().nonnegative().nullable().optional(),dimensions:z.record(z.unknown()).optional()}).strict();
const decision=scope.extend({kind:z.literal("decision"),component,decision:z.enum(["keep_postgres","evaluate_extraction","approve_extraction","reject_extraction"]),rationale:z.string(),thresholds:z.record(z.unknown()).optional(),measurement_ids:z.array(z.string().uuid()).max(100).optional()}).strict();
export const dynamic="force-dynamic";
export async function GET(request:Request){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;try{const url=new URL(request.url);const input=scope.parse({workspace_id:url.searchParams.get("workspace_id"),project_id:url.searchParams.get("project_id")});const selected=url.searchParams.get("component");const componentValue=selected?component.parse(selected):undefined;const [measurements,decisions]=await Promise.all([listScaleMeasurements({workspaceId:input.workspace_id,projectId:input.project_id,component:componentValue},authenticated.session.principalId),listScaleDecisions({workspaceId:input.workspace_id,projectId:input.project_id},authenticated.session.principalId)]);return jsonSuccess({measurements,decisions},context);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);if(error instanceof FoundationServiceError)return ecosystemServiceError(error,context);return jsonError("OPERATION_FAILED",context,500);}}
export async function POST(request:Request){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;const key=request.headers.get("idempotency-key")?.trim();if(!key)return jsonError("VALIDATION_FAILED",context,400);try{const body=await request.json();if(body?.kind==="measurement"){const input=measurement.parse(body);const result=await recordScaleMeasurement({workspaceId:input.workspace_id,projectId:input.project_id,component:input.component,metricName:input.metric_name,windowStart:input.window_start,windowEnd:input.window_end,sampleCount:input.sample_count,p50:input.p50,p95:input.p95,p99:input.p99,maximum:input.maximum,dimensions:input.dimensions},ecosystemMutationContext(authenticated.session.principalId,context,key));return jsonSuccess(mutationEnvelope("measurement",result),context,result.replayed?200:201);}const input=decision.parse(body);const result=await createScaleDecision({workspaceId:input.workspace_id,projectId:input.project_id,component:input.component,decision:input.decision,rationale:input.rationale,thresholds:input.thresholds,measurementIds:input.measurement_ids},ecosystemMutationContext(authenticated.session.principalId,context,key));return jsonSuccess(mutationEnvelope("decision",result),context,result.replayed?200:201);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);if(error instanceof FoundationServiceError)return ecosystemServiceError(error,context);return jsonError("OPERATION_FAILED",context,500);}}
