import { z } from "zod";
import { authenticatedRequest, jsonError, jsonSuccess, requestContext } from "@/api";
import { FoundationServiceError } from "@/services/foundation";
import { readWorkspaceResidencyPolicy, upsertWorkspaceResidencyPolicy } from "@/services/enterprise-controls";
import { ecosystemMutationContext, ecosystemServiceError, mutationEnvelope } from "../../ecosystem/response";

const scope=z.object({workspace_id:z.string().uuid()}).strict();
const schema=scope.extend({expected_revision:z.number().int().positive().optional(),primary_region:z.string(),allowed_regions:z.array(z.string()).min(1).max(20),export_region:z.string().nullable().optional(),customer_managed_key_reference:z.string().max(500).nullable().optional(),policy_state:z.enum(["draft","enforced","suspended"]).optional()}).strict();
export const dynamic="force-dynamic";
export async function GET(request:Request){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;try{const url=new URL(request.url);const input=scope.parse({workspace_id:url.searchParams.get("workspace_id")});return jsonSuccess(await readWorkspaceResidencyPolicy(input.workspace_id,authenticated.session.principalId),context);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);if(error instanceof FoundationServiceError)return ecosystemServiceError(error,context);return jsonError("OPERATION_FAILED",context,500);}}
export async function PUT(request:Request){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;const key=request.headers.get("idempotency-key")?.trim();if(!key)return jsonError("VALIDATION_FAILED",context,400);try{const input=schema.parse(await request.json());const result=await upsertWorkspaceResidencyPolicy({workspaceId:input.workspace_id,expectedRevision:input.expected_revision,primaryRegion:input.primary_region,allowedRegions:input.allowed_regions,exportRegion:input.export_region,customerManagedKeyReference:input.customer_managed_key_reference,policyState:input.policy_state},ecosystemMutationContext(authenticated.session.principalId,context,key));return jsonSuccess(mutationEnvelope("residency",result),context,result.replayed?200:201);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);if(error instanceof FoundationServiceError)return ecosystemServiceError(error,context);return jsonError("OPERATION_FAILED",context,500);}}
