import { z } from "zod";
import { authenticatedRequest, jsonError, jsonSuccess, requestContext } from "@/api";
import { FoundationServiceError } from "@/services/foundation";
import { archiveTypedRelationship, decideSuggestedRelationship } from "@/services/typed-relationships";
import { ecosystemMutationContext, ecosystemServiceError, mutationEnvelope } from "../../ecosystem/response";

const schema=z.object({workspace_id:z.string().uuid(),project_id:z.string().uuid(),expected_revision:z.number().int().positive(),action:z.enum(["accept","reject","archive"])}).strict();
export const dynamic="force-dynamic";
export async function PATCH(request:Request,{params}:{params:Promise<{relationshipId:string}>}){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;const key=request.headers.get("idempotency-key")?.trim();if(!key)return jsonError("VALIDATION_FAILED",context,400);try{const {relationshipId}=await params;const id=z.string().uuid().parse(relationshipId);const input=schema.parse(await request.json());const mutation=ecosystemMutationContext(authenticated.session.principalId,context,key);const result=input.action==="archive"?await archiveTypedRelationship({workspaceId:input.workspace_id,projectId:input.project_id,relationshipId:id,expectedRevision:input.expected_revision},mutation):await decideSuggestedRelationship({workspaceId:input.workspace_id,projectId:input.project_id,relationshipId:id,expectedRevision:input.expected_revision,decision:input.action},mutation);return jsonSuccess(mutationEnvelope("relationship",result),context,result.replayed?200:201);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);if(error instanceof FoundationServiceError)return ecosystemServiceError(error,context);return jsonError("OPERATION_FAILED",context,500);}}
