"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { GitBranch, Network, Plus, RefreshCw, Shapes, Upload } from "lucide-react";
import styles from "@/app/map/map.module.css";

type CanvasSummary={id:string;title:string;visibility:"private"|"project";revision:number;currentRevisionId:string};
type CanvasElement={id:string;kind:string;entityType:string|null;entityId:string|null;content:Record<string,unknown>;geometry:Record<string,unknown>;revision:number};
type CanvasScene=CanvasSummary&{elements:CanvasElement[]};
type GraphView={id:string;name:string;visibility:"private"|"project";rootEntities:Array<{type:string;id:string}>;revision:number};
type GraphResult={nodes:Array<{type:string;id:string;title:string;status:string|null}>;edges:Array<{id:string;typeKey:string;displayName:string;source:{type:string;id:string};target:{type:string;id:string}}>;depthReached:number;truncated:boolean};
type ScaleDecision={id:string;component:string;decision:string;rationale:string};
type MermaidPreview={id:string;warnings:string[];losses:string[];sourceText:string|null};
type Envelope<T>={data:T;error?:{message?:string}};

async function api<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{cache:"no-store",...init});const payload=await response.json().catch(()=>({})) as Envelope<T>;if(!response.ok)throw new Error(payload.error?.message??`Request failed (${response.status})`);return payload.data;}
const key=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`;

export function KnowledgeMapWorkspace({workspaceId,projectId}:{workspaceId?:string;projectId?:string}){
  const [mode,setMode]=useState<"graph"|"canvas">("graph");
  const [canvases,setCanvases]=useState<CanvasSummary[]>([]);
  const [views,setViews]=useState<GraphView[]>([]);
  const [decisions,setDecisions]=useState<ScaleDecision[]>([]);
  const [selectedCanvasId,setSelectedCanvasId]=useState<string|null>(null);
  const [canvas,setCanvas]=useState<CanvasScene|null>(null);
  const [graph,setGraph]=useState<GraphResult|null>(null);
  const [rootType,setRootType]=useState("page");
  const [rootId,setRootId]=useState("");
  const [canvasTitle,setCanvasTitle]=useState("Planning canvas");
  const [stickyText,setStickyText]=useState("");
  const [mermaid,setMermaid]=useState("flowchart LR\nA[Idea] --> B[Decision]");
  const [preview,setPreview]=useState<MermaidPreview|null>(null);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState<string|null>(null);

  const scope=useMemo(()=>workspaceId&&projectId?`workspace_id=${encodeURIComponent(workspaceId)}&project_id=${encodeURIComponent(projectId)}`:null,[workspaceId,projectId]);
  const load=useCallback(async()=>{if(!scope)return;setBusy(true);setError(null);try{const [canvasList,viewList,governance]=await Promise.all([api<CanvasSummary[]>(`/api/v1/canvases?${scope}`),api<GraphView[]>(`/api/v1/graph-views?${scope}`),api<{decisions:ScaleDecision[]}>(`/api/v1/scale-governance?${scope}`)]);setCanvases(canvasList);setViews(viewList);setDecisions(governance.decisions);if(!selectedCanvasId&&canvasList[0])setSelectedCanvasId(canvasList[0].id);}catch(value){setError(value instanceof Error?value.message:"Unable to load map workspace.");}finally{setBusy(false);}},[scope,selectedCanvasId]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(!scope||!selectedCanvasId){setCanvas(null);return;}void api<CanvasScene>(`/api/v1/canvases/${selectedCanvasId}?${scope}`).then(setCanvas).catch((value)=>setError(value instanceof Error?value.message:"Unable to load Canvas."));},[scope,selectedCanvasId]);

  if(!workspaceId||!projectId)return <main className={styles.shell}><div className={styles.notice}><h1>Map & Canvas</h1><p>Open this workspace with both project identifiers.</p><code>?workspace_id=&lt;uuid&gt;&amp;project_id=&lt;uuid&gt;</code></div></main>;

  async function createCanvas(){setBusy(true);setError(null);try{const result=await api<{canvas:CanvasScene}>("/api/v1/canvases",{method:"POST",headers:{"content-type":"application/json","idempotency-key":key("canvas")},body:JSON.stringify({workspace_id:workspaceId,project_id:projectId,title:canvasTitle,visibility:"private"})});setSelectedCanvasId(result.canvas.id);await load();}catch(value){setError(value instanceof Error?value.message:"Unable to create Canvas.");}finally{setBusy(false);}}
  async function addSticky(){if(!canvas||!stickyText.trim())return;setBusy(true);setError(null);try{const result=await api<{canvas:CanvasScene}>(`/api/v1/canvases/${canvas.id}/commands`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":key("canvas-command")},body:JSON.stringify({workspace_id:workspaceId,project_id:projectId,expected_revision:canvas.revision,client_id:"map-workspace",client_sequence:Date.now(),command:{type:"element.create",element:{kind:"sticky",content:{text:stickyText.trim()},geometry:{x:80+canvas.elements.length*20,y:80+canvas.elements.length*18,width:220,height:140},zIndex:canvas.elements.length}}})});setCanvas(result.canvas);setStickyText("");await load();}catch(value){setError(value instanceof Error?value.message:"Unable to add Canvas element.");}finally{setBusy(false);}}
  async function runGraph(){if(!rootId.trim())return;setBusy(true);setError(null);try{setGraph(await api<GraphResult>("/api/v1/graph-traversal",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspace_id:workspaceId,project_id:projectId,root_entities:[{type:rootType,id:rootId.trim()}],traversal:{depth:2,nodeLimit:250,edgeLimit:500}})}));}catch(value){setError(value instanceof Error?value.message:"Unable to traverse graph.");}finally{setBusy(false);}}
  async function saveGraphView(){if(!rootId.trim())return;setBusy(true);setError(null);try{await api("/api/v1/graph-views",{method:"POST",headers:{"content-type":"application/json","idempotency-key":key("graph-view")},body:JSON.stringify({workspace_id:workspaceId,project_id:projectId,name:`${rootType} map`,visibility:"private",root_entities:[{type:rootType,id:rootId.trim()}],traversal:{depth:2,nodeLimit:250,edgeLimit:500}})});await load();}catch(value){setError(value instanceof Error?value.message:"Unable to save graph view.");}finally{setBusy(false);}}
  async function previewImport(){if(!canvas)return;setBusy(true);setError(null);try{setPreview(await api<MermaidPreview>("/api/v1/mermaid-interchange/previews",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({direction:"import",workspace_id:workspaceId,project_id:projectId,canvas_id:canvas.id,source_text:mermaid})}));}catch(value){setError(value instanceof Error?value.message:"Unable to preview Mermaid import.");}finally{setBusy(false);}}
  async function executeImport(){if(!preview||!canvas)return;setBusy(true);setError(null);try{await api(`/api/v1/mermaid-interchange/previews/${preview.id}/execute`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":key("mermaid-import")},body:JSON.stringify({workspace_id:workspaceId,project_id:projectId,client_id:"map-workspace"})});setPreview(null);setCanvas(await api<CanvasScene>(`/api/v1/canvases/${canvas.id}?${scope}`));await load();}catch(value){setError(value instanceof Error?value.message:"Unable to execute Mermaid import.");}finally{setBusy(false);}}

  return <main className={styles.shell}>
    <header className={styles.header}><div><h1>Map & Canvas</h1><p>Typed relationships, permission-filtered graph traversal, revisioned scenes, and bounded Mermaid interchange.</p></div><div className={styles.status}><span className={styles.badge}>PostgreSQL graph</span><span className={styles.badge}>Optimistic scene revisions</span><span className={styles.badge}>No hidden entity placeholders</span></div></header>
    {error&&<p className={styles.error}>{error}</p>}
    <div className={styles.grid}>
      <aside className={styles.panel}><div className={styles.panelHeader}><h2>Workspace</h2><button className={styles.button} onClick={()=>void load()} disabled={busy}><RefreshCw size={15}/></button></div><div className={`${styles.panelBody} ${styles.stack}`}>
        <div className={styles.tabs}><button data-active={mode==="graph"} onClick={()=>setMode("graph")}><Network size={15}/> Graph</button><button data-active={mode==="canvas"} onClick={()=>setMode("canvas")}><Shapes size={15}/> Canvas</button></div>
        {mode==="graph"?<><div className={styles.field}><label>Root entity type</label><select value={rootType} onChange={(event)=>setRootType(event.target.value)}><option value="page">Page</option><option value="issue">Issue</option><option value="todo">To-do</option><option value="calendar_entry">Calendar entry</option><option value="canvas">Canvas</option></select></div><div className={styles.field}><label>Root UUID</label><input value={rootId} onChange={(event)=>setRootId(event.target.value)} placeholder="Entity UUID"/></div><div className={styles.row}><button className={`${styles.button} ${styles.buttonPrimary}`} onClick={()=>void runGraph()} disabled={busy||!rootId.trim()}><GitBranch size={15}/> Traverse</button><button className={styles.button} onClick={()=>void saveGraphView()} disabled={busy||!rootId.trim()}>Save view</button></div><div className={styles.list}>{views.map((view)=><button key={view.id} onClick={()=>{const root=view.rootEntities[0];if(root){setRootType(root.type);setRootId(root.id);}}}><strong>{view.name}</strong><small>{view.visibility} · {view.rootEntities.length} roots</small></button>)}</div></>:<><div className={styles.field}><label>New Canvas title</label><input value={canvasTitle} onChange={(event)=>setCanvasTitle(event.target.value)}/></div><button className={`${styles.button} ${styles.buttonPrimary}`} onClick={()=>void createCanvas()} disabled={busy}><Plus size={15}/> Create Canvas</button><div className={styles.list}>{canvases.map((item)=><button key={item.id} data-active={item.id===selectedCanvasId} onClick={()=>setSelectedCanvasId(item.id)}><strong>{item.title}</strong><small>{item.visibility} · revision {item.revision}</small></button>)}</div></>}
        <div><small className={styles.warning}>Scale decisions</small><div className={styles.list}>{decisions.slice(0,5).map((decision)=><button key={decision.id}><strong>{decision.component}</strong><small>{decision.decision}</small></button>)}</div></div>
      </div></aside>
      <section className={styles.panel}><div className={styles.panelHeader}><h2>{mode==="graph"?"Permission-filtered graph":"Revisioned Canvas"}</h2><span className={styles.badge}>{busy?"Working…":"Ready"}</span></div><div className={`${styles.panelBody} ${styles.stack}`}>
        {mode==="graph"?<>{graph?<><div className={styles.summary}><div className={styles.metric}><strong>{graph.nodes.length}</strong><span>visible nodes</span></div><div className={styles.metric}><strong>{graph.edges.length}</strong><span>visible edges</span></div><div className={styles.metric}><strong>{graph.depthReached}</strong><span>depth reached</span></div></div><div className={styles.graph}><div className={styles.stack}><h3>Nodes</h3>{graph.nodes.map((node)=><div className={styles.node} key={`${node.type}:${node.id}`}><strong>{node.title}</strong><small>{node.type} · {node.status??"active"}</small></div>)}</div><div className={styles.stack}><h3>Edges</h3>{graph.edges.map((edge)=><div className={styles.edge} key={edge.id}><strong>{edge.displayName}</strong><small>{edge.source.type} → {edge.target.type}</small></div>)}</div></div>{graph.truncated&&<p className={styles.warning}>The traversal reached its configured budget.</p>}</>:<p className={styles.empty}>Choose an authorized entity and run a bounded traversal.</p>}</>:canvas?<><div className={styles.summary}><div className={styles.metric}><strong>{canvas.revision}</strong><span>scene revision</span></div><div className={styles.metric}><strong>{canvas.elements.length}</strong><span>visible elements</span></div><div className={styles.metric}><strong>{canvas.visibility}</strong><span>visibility</span></div></div><div className={styles.row}><div className={`${styles.field} ${styles.grow}`}><label>New sticky</label><input value={stickyText} onChange={(event)=>setStickyText(event.target.value)} placeholder="Capture an idea"/></div><button className={`${styles.button} ${styles.buttonPrimary}`} onClick={()=>void addSticky()} disabled={busy||!stickyText.trim()}><Plus size={15}/> Add</button></div><div className={styles.canvasGrid}>{canvas.elements.map((element)=><article key={element.id} className={`${styles.element} ${element.kind==="entity_card"?styles.entity:""}`}><strong>{typeof element.content.text==="string"?element.content.text:element.kind}</strong><small>{element.kind} · revision {element.revision}</small></article>)}</div><div className={styles.field}><label>Mermaid flowchart source</label><textarea value={mermaid} onChange={(event)=>setMermaid(event.target.value)}/></div><div className={styles.row}><button className={styles.button} onClick={()=>void previewImport()} disabled={busy}><Upload size={15}/> Preview import</button>{preview&&<button className={`${styles.button} ${styles.buttonPrimary}`} onClick={()=>void executeImport()} disabled={busy}>Apply {preview.warnings.length?"with warnings":"preview"}</button>}</div>{preview&&<div className={styles.warning}>{preview.warnings.map((item)=><p key={item}>{item}</p>)}{preview.losses.map((item)=><p key={item}>{item}</p>)}</div>}</>:<p className={styles.empty}>Create or select a Canvas.</p>}
      </div></section>
    </div>
  </main>;
}
