import { z } from "zod";
import { authenticatedRequest, jsonError, jsonSuccess, requestContext } from "@/api";
import { createProjectRepositoryLink, listProjectRepositoryLinks } from "@/services/github-repositories";
import { githubApiError, githubMutationContext } from "../github/response";

const scope=z.object({workspace_id:z.string().uuid(),project_id:z.string().uuid()}).strict();
const createSchema=scope.extend({repository_id:z.string().uuid(),display_name:z.string().trim().min(1).max(200).optional(),write_policy:z.enum(["disabled","pull_request_only","direct_allowed"]).optional(),include_rules:z.array(z.string().min(1).max(500)).min(1).max(100).optional(),exclude_rules:z.array(z.string().min(1).max(500)).max(100).optional()}).strict();
export const dynamic="force-dynamic";

export async function GET(request:Request){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;try{const url=new URL(request.url);const input=scope.parse({workspace_id:url.searchParams.get("workspace_id"),project_id:url.searchParams.get("project_id")});return jsonSuccess(await listProjectRepositoryLinks({workspaceId:input.workspace_id,projectId:input.project_id},authenticated.session.principalId),context);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);return githubApiError(error,context);}}

export async function POST(request:Request){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;const key=request.headers.get("idempotency-key")?.trim();if(!key)return jsonError("VALIDATION_FAILED",context,400);try{const input=createSchema.parse(await request.json());const result=await createProjectRepositoryLink({workspaceId:input.workspace_id,projectId:input.project_id,repositoryId:input.repository_id,displayName:input.display_name,writePolicy:input.write_policy,includeRules:input.include_rules,excludeRules:input.exclude_rules},githubMutationContext(authenticated.session.principalId,context,key));return jsonSuccess({repository_link:result.data,activity_id:result.activityId,outbox_event_id:result.outboxEventId,replayed:result.replayed},context,result.replayed?200:201);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);return githubApiError(error,context);}}
