import { z } from "zod";
import { authenticatedRequest, jsonError, jsonSuccess, requestContext } from "@/api";
import { readWorkspaceStoragePolicy, setWorkspaceStoragePolicy } from "@/services/operational-readiness";
import { workspaceAdminError, workspaceMutationContext } from "../../../workspace-admin/response";

const schema=z.object({provider:z.enum(["filesystem","s3"]),bucket:z.string().trim().min(1).max(255).nullable().optional(),region:z.string().trim().min(1).max(120).nullable().optional(),endpoint:z.string().url().nullable().optional(),key_prefix:z.string().max(500).optional(),credential_ref:z.string().trim().min(1).max(500).nullable().optional(),encryption_key_ref:z.string().trim().min(1).max(500).nullable().optional(),force_path_style:z.boolean().optional(),state:z.enum(["active","disabled"]).optional(),expected_revision:z.number().int().positive().optional()}).strict();
export const dynamic="force-dynamic";

export async function GET(request:Request,{params}:{params:Promise<{workspaceId:string}>}){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;try{const {workspaceId}=await params;return jsonSuccess(await readWorkspaceStoragePolicy(z.string().uuid().parse(workspaceId),authenticated.session.principalId),context);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);return workspaceAdminError(error,context);}}

export async function PUT(request:Request,{params}:{params:Promise<{workspaceId:string}>}){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;const key=request.headers.get("idempotency-key")?.trim();if(!key)return jsonError("VALIDATION_FAILED",context,400);try{const {workspaceId}=await params;const input=schema.parse(await request.json());const result=await setWorkspaceStoragePolicy({workspaceId:z.string().uuid().parse(workspaceId),provider:input.provider,bucket:input.bucket,region:input.region,endpoint:input.endpoint,keyPrefix:input.key_prefix,credentialRef:input.credential_ref,encryptionKeyRef:input.encryption_key_ref,forcePathStyle:input.force_path_style,state:input.state,expectedRevision:input.expected_revision},workspaceMutationContext(authenticated.session.principalId,context,key));return jsonSuccess({storage_policy:result.data,activity_id:result.activityId,outbox_event_id:result.outboxEventId,replayed:result.replayed},context);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);return workspaceAdminError(error,context);}}
