import { z } from "zod";
import { authenticatedRequest, jsonError, jsonSuccess, requestContext } from "@/api";
import { FoundationServiceError } from "@/services/foundation";
import { createTypedRelationship, listEntityRelationships } from "@/services/typed-relationships";
import { ecosystemMutationContext, ecosystemServiceError, mutationEnvelope } from "../ecosystem/response";

const entity=z.enum(["page","issue","todo","calendar_entry","canvas"]);
const scope=z.object({workspace_id:z.string().uuid(),project_id:z.string().uuid()}).strict();
const schema=scope.extend({relationship_type_id:z.string().uuid(),source:z.object({type:entity,id:z.string().uuid()}).strict(),target:z.object({type:entity,id:z.string().uuid()}).strict(),provenance:z.enum(["explicit","derived","suggested","canvas_only"]).optional(),canvas_id:z.string().uuid().nullable().optional(),confidence:z.number().min(0).max(1).nullable().optional(),metadata:z.record(z.unknown()).optional()}).strict();
export const dynamic="force-dynamic";
export async function GET(request:Request){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;try{const url=new URL(request.url);const input=scope.parse({workspace_id:url.searchParams.get("workspace_id"),project_id:url.searchParams.get("project_id")});return jsonSuccess(await listEntityRelationships({workspaceId:input.workspace_id,projectId:input.project_id,entityType:entity.parse(url.searchParams.get("entity_type")),entityId:z.string().uuid().parse(url.searchParams.get("entity_id")),includeSuggested:url.searchParams.get("include_suggested")==="true",limit:Number(url.searchParams.get("limit")??200)},authenticated.session.principalId),context);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);if(error instanceof FoundationServiceError)return ecosystemServiceError(error,context);return jsonError("OPERATION_FAILED",context,500);}}
export async function POST(request:Request){const context=requestContext(request);const authenticated=await authenticatedRequest(request,context);if(!authenticated.ok)return authenticated.response;const key=request.headers.get("idempotency-key")?.trim();if(!key)return jsonError("VALIDATION_FAILED",context,400);try{const input=schema.parse(await request.json());const result=await createTypedRelationship({workspaceId:input.workspace_id,projectId:input.project_id,relationshipTypeId:input.relationship_type_id,source:input.source,target:input.target,provenance:input.provenance,canvasId:input.canvas_id,confidence:input.confidence,metadata:input.metadata},ecosystemMutationContext(authenticated.session.principalId,context,key));return jsonSuccess(mutationEnvelope("relationship",result),context,result.replayed?200:201);}catch(error){if(error instanceof z.ZodError)return jsonError("VALIDATION_FAILED",context,400);if(error instanceof FoundationServiceError)return ecosystemServiceError(error,context);return jsonError("OPERATION_FAILED",context,500);}}
